### ISSUE TITLE
Problems with set_cuda_device

### ISSUE THREAD

**Issue by ead-ru** [madhawav/YOLO3-4-Py#101]
Got error: "AttributeError: module 'pydarknet' has no attribute 'set_cuda_device'" when trying to set GPU after installing with GPU=1. Works fine if set USE_GPU=True in setup.py before installation. Install script:
```
#!/bin/bash
export DARKNET_HOME=/darknet
export OPENCV=1
export GPU=1
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DARKNET_HOME
export CUDA_HOME=/usr/local/cuda
pip3 install .
```
Darknet built with GPU=1.

**Comment by madhawav** [comment]
This issue is fixed with #118.
