### ISSUE TITLE
I am trying to install yolo34py in ubuntu 19.04 and it fails everytime with this error message

### ISSUE THREAD

**Issue by Dheeraj-Meka** [madhawav/YOLO3-4-Py#102]
Collecting yolo34py
  Using cached https://files.pythonhosted.org/packages/fa/25/91792cac161adf97d0dd9c0954c0f2c9d8c93bf9c5404ddff9fcd4b58ecf/yolo34py-0.1rc12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3wt38e8c/yolo34py/setup.py", line 47, in <module>
        if USE_CV & (get_libs("opencv") == '' or get_cflags("opencv") == ''):
      File "/tmp/pip-install-3wt38e8c/yolo34py/util.py", line 85, in get_libs
        proc = subprocess.Popen(shlex.split(command), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config': 'pkg-config'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-3wt38e8c/yolo34py/

**Comment by rofly** [comment]
You could install package-config and will probably work just fine.
Ubuntu: 
```
apt-get install -y pkg-config
pip3 install pkgconfig
```

**Comment by madhawav** [comment]
Hi @Dheeraj-Meka, did the above solution by @rofly solves your issue?
