### ISSUE TITLE
Initializing Detector() crashes google colab notebook.

### ISSUE THREAD

**Issue by real-Piyush-Sharma** [madhawav/YOLO3-4-Py#112]
running:
`net = Detector(bytes("cfg/yolov3.cfg", encoding="utf-8"), bytes("weights/yolov3.weights", encoding="utf-8"), 0, bytes("cfg/coco.data",encoding="utf-8"))`
from example at pypi crashes the google colab notebook.

**Comment by GeoffSion** [comment]
I have the same problem on Ubuntu using a conda env, the output error is simply "python: Unknown error 121950488"  (the number changes everytime)

**Comment by GeoffSion** [comment]
I noticed that since I'm working from home, my vpn was blocking me from accessing certain pages. So the `sh download_models.sh` command was only creating the _cfg/coco.data_, _cfg/yolov3.cfg_ and _data.coco.names_ files but they were empty.
@real-Piyush-Sharma, check these files

**Comment by madhawav** [comment]
Refer the following link for a working example in Google Colab.
https://colab.research.google.com/drive/1DGzgpb8VR69EqSEb3bco6nSZQ_59eUZf?usp=sharing
