### ISSUE TITLE
KeyError: 'DARKNET_HOME'

### ISSUE THREAD

**Issue by dhiegomaga** [madhawav/YOLO3-4-Py#114]
Just following the "Installation from source" and tried running `python3 image_demo.py`
It will yield the following error:

```shell
Loading weights from weights/yolov3.weights...Done!
Traceback (most recent call last):
  File "image_demo.py", line 10, in <module>
    img = cv2.imread(os.path.join(os.environ["DARKNET_HOME"],"data/dog.jpg"))
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'DARKNET_HOME'
```

**Comment by madhawav** [comment]
Hi @dhiegomaga 
Thank you for showing this issue. It's a bug in the demo script. I will fix it.

Replace line 10 of image_demo.py with the path to any image file you prefer like below:
```python
img = cv2.imread("[PATH TO IMAGE FILE]")
```

**Comment by madhawav** [comment]
Hi @dhiegomaga 
I have modified image_demo.py to accept the path to a source image as a command-line argument.
