### ISSUE TITLE
"g++: error: : No such file or directory, Ubuntu 20.04

### ISSUE THREAD

**Issue by matteoTaiana** [madhawav/YOLO3-4-Py#116]
Hi guys,
I am having trouble installing the package via pip.

My configuration is: Ubuntu 20.04, g++ 8.4.0, CUDA 10.2.
I have Cython installed, in case that matters.

**Sorry: while I was editing, I realised  issue 113 deals with the same problem:
https://github.com/madhawav/YOLO3-4-Py/issues/113

I tried not to submit my issue, but somehow it got posted and now I cannot delete it.
Please, delete it, if you can.**

Anyway, this is the command I run, followed by the output I get. 
Thanks everyone for the support!

$ pip install yolo34py-gpu

Collecting yolo34py-gpu
  Using cached yolo34py-gpu-0.1rc12.tar.gz (66 kB)
Requirement already satisfied: cython>=0.27 in /home/matteo/.local/lib/python3.8/site-packages (from yolo34py-gpu) (0.29.17)
Requirement already satisfied: requests in /home/matteo/.conda/envs/AEDv0/lib/python3.8/site-packages (from yolo34py-gpu) (2.23.0)
Requirement already satisfied: numpy in /home/matteo/.local/lib/python3.8/site-packages (from yolo34py-gpu) (1.18.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/matteo/.conda/envs/AEDv0/lib/python3.8/site-packages (from requests->yolo34py-gpu) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /home/matteo/.conda/envs/AEDv0/lib/python3.8/site-packages (from requests->yolo34py-gpu) (2020.4.5.1)
Requirement already satisfied: idna<3,>=2.5 in /home/matteo/.conda/envs/AEDv0/lib/python3.8/site-packages (from requests->yolo34py-gpu) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/matteo/.conda/envs/AEDv0/lib/python3.8/site-packages (from requests->yolo34py-gpu) (3.0.4)
Building wheels for collected packages: yolo34py-gpu
  Building wheel for yolo34py-gpu (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/matteo/.conda/envs/AEDv0/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m_psp5e6/yolo34py-gpu/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m_psp5e6/yolo34py-gpu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-b_6p6awq
       cwd: /tmp/pip-install-m_psp5e6/yolo34py-gpu/
  Complete output (115 lines):
  INFO:root:Selected Darknet Branch: yolo34py-intergration-nocv from Darknet Fork 'https://github.com/madhawav/darknet/'
  /home/matteo/.conda/envs/AEDv0/lib/python3.8/site-packages/setuptools/dist.py:454: UserWarning: Normalizing '0.1.rc12' to '0.1rc12'
    warnings.warn(tmpl.format(**locals()))
  running bdist_wheel
  running build
  INFO:root:Temp Path: /tmp/darknet
  INFO:root:Downloading darknet
  INFO:root:Extracting darknet
  INFO:root:Building darknet
  ./src/gemm.c: In function ‘time_gpu’:
  ./src/gemm.c:232:9: warning: ‘cudaThreadSynchronize’ is deprecated [-Wdeprecated-declarations]
           cudaThreadSynchronize();
           ^~~~~~~~~~~~~~~~~~~~~
  In file included from /usr/local/cuda/include/cuda_runtime.h:96,
                   from include/darknet.h:14,
                   from ./src/utils.h:5,
                   from ./src/gemm.c:2:
  /usr/local/cuda/include/cuda_runtime_api.h:957:57: note: declared here
   extern __CUDA_DEPRECATED __host__ cudaError_t CUDARTAPI cudaThreadSynchronize(void);
                                                           ^~~~~~~~~~~~~~~~~~~~~
  INFO:root:Darknet building successful
  INFO:root:Moving to /tmp/pip-install-m_psp5e6/yolo34py-gpu/__libdarknet/libdarknet.so
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/__libdarknet
  copying __libdarknet/__init__.py -> build/lib.linux-x86_64-3.8/__libdarknet
  running egg_info
  writing yolo34py_gpu.egg-info/PKG-INFO
  writing dependency_links to yolo34py_gpu.egg-info/dependency_links.txt
  writing requirements to yolo34py_gpu.egg-info/requires.txt
  writing top-level names to yolo34py_gpu.egg-info/top_level.txt
  reading manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
  copying __libdarknet/libdarknet.so -> build/lib.linux-x86_64-3.8/__libdarknet
  running build_ext
  skipping 'pydarknet.cpp' Cython extension (up-to-date)
  building 'pydarknet' extension
  creating build/temp.linux-x86_64-3.8
  gcc -pthread -B /home/matteo/.conda/envs/AEDv0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CV=0 -I/home/matteo/.local/lib/python3.8/site-packages/numpy/core/include -I/tmp/darknet/darknet-yolo34py-intergration-nocv/include -I/tmp/darknet/darknet-yolo34py-intergration-nocv/src -I/home/matteo/.conda/envs/AEDv0/include/python3.8 -c pydarknet.cpp -o build/temp.linux-x86_64-3.8/pydarknet.o -I/usr/include/python3.8 -I/usr/include/x86_64-linux-gnu/python3.8
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from /home/matteo/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832,
                   from /home/matteo/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /home/matteo/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from pydarknet.cpp:580:
  /home/matteo/.local/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^~~~~~~
  pydarknet.cpp: In function ‘int __Pyx_modinit_type_init_code()’:
  pydarknet.cpp:6328:31: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
     __pyx_type_9pydarknet_Image.tp_print = 0;
                                 ^~~~~~~~
  In file included from /home/matteo/.conda/envs/AEDv0/include/python3.8/object.h:746,
                   from /home/matteo/.conda/envs/AEDv0/include/python3.8/pytime.h:6,
                   from /home/matteo/.conda/envs/AEDv0/include/python3.8/Python.h:85,
                   from pydarknet.cpp:4:
  /home/matteo/.conda/envs/AEDv0/include/python3.8/cpython/object.h:260:63: note: declared here
       Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
                                                                 ^
  pydarknet.cpp:6328:31: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
     __pyx_type_9pydarknet_Image.tp_print = 0;
                                 ^~~~~~~~
  In file included from /home/matteo/.conda/envs/AEDv0/include/python3.8/object.h:746,
                   from /home/matteo/.conda/envs/AEDv0/include/python3.8/pytime.h:6,
                   from /home/matteo/.conda/envs/AEDv0/include/python3.8/Python.h:85,
                   from pydarknet.cpp:4:
  /home/matteo/.conda/envs/AEDv0/include/python3.8/cpython/object.h:260:63: note: declared here
       Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
                                                                 ^
  pydarknet.cpp:6328:31: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
     __pyx_type_9pydarknet_Image.tp_print = 0;
                                 ^~~~~~~~
  In file included from /home/matteo/.conda/envs/AEDv0/include/python3.8/object.h:746,
                   from /home/matteo/.conda/envs/AEDv0/include/python3.8/pytime.h:6,
                   from /home/matteo/.conda/envs/AEDv0/include/python3.8/Python.h:85,
                   from pydarknet.cpp:4:
  /home/matteo/.conda/envs/AEDv0/include/python3.8/cpython/object.h:260:63: note: declared here
       Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
                                                                 ^
  pydarknet.cpp:6336:34: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
     __pyx_type_9pydarknet_Detector.tp_print = 0;
                                    ^~~~~~~~
  In file included from /home/matteo/.conda/envs/AEDv0/include/python3.8/object.h:746,
                   from /home/matteo/.conda/envs/AEDv0/include/python3.8/pytime.h:6,
                   from /home/matteo/.conda/envs/AEDv0/include/python3.8/Python.h:85,
                   from pydarknet.cpp:4:
  /home/matteo/.conda/envs/AEDv0/include/python3.8/cpython/object.h:260:63: note: declared here
       Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
                                                                 ^
  pydarknet.cpp:6336:34: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
     __pyx_type_9pydarknet_Detector.tp_print = 0;
                                    ^~~~~~~~
  In file included from /home/matteo/.conda/envs/AEDv0/include/python3.8/object.h:746,
                   from /home/matteo/.conda/envs/AEDv0/include/python3.8/pytime.h:6,
                   from /home/matteo/.conda/envs/AEDv0/include/python3.8/Python.h:85,
                   from pydarknet.cpp:4:
  /home/matteo/.conda/envs/AEDv0/include/python3.8/cpython/object.h:260:63: note: declared here
       Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
                                                                 ^
  pydarknet.cpp:6336:34: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
     __pyx_type_9pydarknet_Detector.tp_print = 0;
                                    ^~~~~~~~
  In file included from /home/matteo/.conda/envs/AEDv0/include/python3.8/object.h:746,
                   from /home/matteo/.conda/envs/AEDv0/include/python3.8/pytime.h:6,
                   from /home/matteo/.conda/envs/AEDv0/include/python3.8/Python.h:85,
                   from pydarknet.cpp:4:
  /home/matteo/.conda/envs/AEDv0/include/python3.8/cpython/object.h:260:63: note: declared here
       Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
                                                                 ^
  gcc -pthread -B /home/matteo/.conda/envs/AEDv0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CV=0 -I/home/matteo/.local/lib/python3.8/site-packages/numpy/core/include -I/tmp/darknet/darknet-yolo34py-intergration-nocv/include -I/tmp/darknet/darknet-yolo34py-intergration-nocv/src -I/home/matteo/.conda/envs/AEDv0/include/python3.8 -c bridge.cpp -o build/temp.linux-x86_64-3.8/bridge.o -I/usr/include/python3.8 -I/usr/include/x86_64-linux-gnu/python3.8
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  g++ -pthread -shared -B /home/matteo/.conda/envs/AEDv0/compiler_compat -L/home/matteo/.conda/envs/AEDv0/lib -Wl,-rpath=/home/matteo/.conda/envs/AEDv0/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/pydarknet.o build/temp.linux-x86_64-3.8/bridge.o -L. -L./__libdarknet -ldarknet -lm -lpthread -o build/lib.linux-x86_64-3.8/pydarknet.cpython-38-x86_64-linux-gnu.so  -Wl,-rpath,/home/matteo/.local/lib/python3.8/site-packages/__libdarknet -Wl,-rpath,/home/matteo/.conda/envs/AEDv0/lib/python3.8/site-packages/__libdarknet
  g++: error: : No such file or directory
  error: command 'g++' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for yolo34py-gpu
  Running setup.py clean for yolo34py-gpu
Failed to build yolo34py-gpu
Installing collected packages: yolo34py-gpu
    Running setup.py install for yolo34py-gpu ... error
    ERROR: Command errored out with exit status 1:
     command: /home/matteo/.conda/envs/AEDv0/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m_psp5e6/yolo34py-gpu/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m_psp5e6/yolo34py-gpu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-oti83e5i/install-record.txt --single-version-externally-managed --compile --install-headers /home/matteo/.conda/envs/AEDv0/include/python3.8/yolo34py-gpu
         cwd: /tmp/pip-install-m_psp5e6/yolo34py-gpu/
    Complete output (57 lines):
    INFO:root:Selected Darknet Branch: yolo34py-intergration-nocv from Darknet Fork 'https://github.com/madhawav/darknet/'
    /home/matteo/.conda/envs/AEDv0/lib/python3.8/site-packages/setuptools/dist.py:454: UserWarning: Normalizing '0.1.rc12' to '0.1rc12'
      warnings.warn(tmpl.format(**locals()))
    running install
    running build
    INFO:root:Temp Path: /tmp/darknet
    INFO:root:Downloading darknet
    INFO:root:Extracting darknet
    INFO:root:Building darknet
    ./src/gemm.c: In function ‘time_gpu’:
    ./src/gemm.c:232:9: warning: ‘cudaThreadSynchronize’ is deprecated [-Wdeprecated-declarations]
             cudaThreadSynchronize();
             ^~~~~~~~~~~~~~~~~~~~~
    In file included from /usr/local/cuda/include/cuda_runtime.h:96,
                     from include/darknet.h:14,
                     from ./src/utils.h:5,
                     from ./src/gemm.c:2:
    /usr/local/cuda/include/cuda_runtime_api.h:957:57: note: declared here
     extern __CUDA_DEPRECATED __host__ cudaError_t CUDARTAPI cudaThreadSynchronize(void);
                                                             ^~~~~~~~~~~~~~~~~~~~~
    INFO:root:Darknet building successful
    INFO:root:Moving to /tmp/pip-install-m_psp5e6/yolo34py-gpu/__libdarknet/libdarknet.so
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/__libdarknet
    copying __libdarknet/__init__.py -> build/lib.linux-x86_64-3.8/__libdarknet
    running egg_info
    writing yolo34py_gpu.egg-info/PKG-INFO
    writing dependency_links to yolo34py_gpu.egg-info/dependency_links.txt
    writing requirements to yolo34py_gpu.egg-info/requires.txt
    writing top-level names to yolo34py_gpu.egg-info/top_level.txt
    reading manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'pydarknet.cpp'
    writing manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
    copying __libdarknet/libdarknet.so -> build/lib.linux-x86_64-3.8/__libdarknet
    running build_ext
    cythoning pydarknet.pyx to pydarknet.cpp
    /home/matteo/.local/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-m_psp5e6/yolo34py-gpu/pydarknet.pxd
      tree = Parsing.p_module(s, pxd, full_module_name)
    building 'pydarknet' extension
    creating build/temp.linux-x86_64-3.8
    gcc -pthread -B /home/matteo/.conda/envs/AEDv0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CV=0 -I/home/matteo/.local/lib/python3.8/site-packages/numpy/core/include -I/tmp/darknet/darknet-yolo34py-intergration-nocv/include -I/tmp/darknet/darknet-yolo34py-intergration-nocv/src -I/home/matteo/.conda/envs/AEDv0/include/python3.8 -c pydarknet.cpp -o build/temp.linux-x86_64-3.8/pydarknet.o -I/usr/include/python3.8 -I/usr/include/x86_64-linux-gnu/python3.8
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/matteo/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832,
                     from /home/matteo/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /home/matteo/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from pydarknet.cpp:614:
    /home/matteo/.local/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^~~~~~~
    gcc -pthread -B /home/matteo/.conda/envs/AEDv0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CV=0 -I/home/matteo/.local/lib/python3.8/site-packages/numpy/core/include -I/tmp/darknet/darknet-yolo34py-intergration-nocv/include -I/tmp/darknet/darknet-yolo34py-intergration-nocv/src -I/home/matteo/.conda/envs/AEDv0/include/python3.8 -c bridge.cpp -o build/temp.linux-x86_64-3.8/bridge.o -I/usr/include/python3.8 -I/usr/include/x86_64-linux-gnu/python3.8
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    g++ -pthread -shared -B /home/matteo/.conda/envs/AEDv0/compiler_compat -L/home/matteo/.conda/envs/AEDv0/lib -Wl,-rpath=/home/matteo/.conda/envs/AEDv0/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/pydarknet.o build/temp.linux-x86_64-3.8/bridge.o -L. -L./__libdarknet -ldarknet -lm -lpthread -o build/lib.linux-x86_64-3.8/pydarknet.cpython-38-x86_64-linux-gnu.so  -Wl,-rpath,/home/matteo/.local/lib/python3.8/site-packages/__libdarknet -Wl,-rpath,/home/matteo/.conda/envs/AEDv0/lib/python3.8/site-packages/__libdarknet
    g++: error: : No such file or directory
    error: command 'g++' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/matteo/.conda/envs/AEDv0/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m_psp5e6/yolo34py-gpu/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m_psp5e6/yolo34py-gpu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-oti83e5i/install-record.txt --single-version-externally-managed --compile --install-headers /home/matteo/.conda/envs/AEDv0/include/python3.8/yolo34py-gpu Check the logs for full command output.

**Comment by KiriUbu** [comment]
Hi ! i have the same Problem. I could solve it by downloading the repo. 
in the folder YOLO3-4-py you will find a setup.py.
you go to line 82 and delete the content in the brackets. So it looks like this

`extra_compiler_flags = [ get_cflags("python3")]
extra_linker_flags = []`

after that you can install the non gpu version with :
`pip install .`

**Comment by madhawav** [comment]
Hi @matteoTaiana 
Have you referred this: https://github.com/madhawav/YOLO3-4-Py/issues/26
