### ISSUE TITLE
get error when i install yolo34py in Windows 8 pro

### ISSUE THREAD

**Issue by falahgs** [madhawav/YOLO3-4-Py#117]
why i got error  when i install yolo34py in my pc windows 8 pro 

Collecting yolo34py
  Downloading yolo34py-0.1rc12.tar.gz (67 kB)
     |████████████████████████████████| 67 kB 10 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\falahgs\appdata\local\programs\python\python37\python.ex
e' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\falahgs\\
AppData\\Local\\Temp\\pip-install-kb3xt9c2\\yolo34py\\setup.py'"'"'; __file__='"
'"'C:\\Users\\falahgs\\AppData\\Local\\Temp\\pip-install-kb3xt9c2\\yolo34py\\set
up.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().rep
lace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'e
xec'"'"'))' egg_info --egg-base 'C:\Users\falahgs\AppData\Local\Temp\pip-pip-egg
-info-srdjpf04'
         cwd: C:\Users\falahgs\AppData\Local\Temp\pip-install-kb3xt9c2\yolo34py\

    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\falahgs\AppData\Local\Temp\pip-install-kb3xt9c2\yolo34py\se
tup.py", line 47, in <module>
        if USE_CV & (get_libs("opencv") == '' or get_cflags("opencv") == ''):
      File "C:\Users\falahgs\AppData\Local\Temp\pip-install-kb3xt9c2\yolo34py\ut
il.py", line 85, in get_libs
        proc = subprocess.Popen(shlex.split(command), stdout=subprocess.PIPE, st
derr=subprocess.PIPE)
      File "c:\users\falahgs\appdata\local\programs\python\python37\lib\subproce
ss.py", line 756, in __init__
        restore_signals, start_new_session)
      File "c:\users\falahgs\appdata\local\programs\python\python37\lib\subproce
ss.py", line 1155, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check th
e logs for full command output.

------------------------------------------------------------------------------------------------

would u please explain how to install in windows os
 thanks for help

**Comment by madhawav** [comment]
Hi,
Unfortunately, we do not support Windows operating system.
