### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by paulaceccon** [madhawav/YOLO3-4-Py#124]
Can't install yolo34py-gpu.

> Collecting yolo34py-gpu (from -r /requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/dc/a3/12c668e54109c5469a8312d757b357dda0b2efc2150043b76b58f6ba75c3/yolo34py-gpu-0.1rc12.tar.gz (66kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-e2b1lq4p/yolo34py-gpu/setup.py", line 5, in <module>
        import numpy as np # TODO: Need a mechanism to ensure numpy is already installed
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-e2b1lq4p/yolo34py-gpu/
The command '/bin/sh -c pip3 install -r /requirements.txt && rm /requirements.txt' returned a non-zero code: 1

- Docker file: 

```FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

RUN apt update && apt install -y \
    python3-dev \
    python3-pip \
    libsm6 \
    libxrender1 \
    libxext6

ADD requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt && rm /requirements.txt

ADD /code /code
WORKDIR /code

CMD ["python3", "main.py"]
```

- Requirements: 

```
numpy
opencv-python==4.1.1.26
tensorflow-gpu==1.14.0
pika==1.1.0
cython==0.29.13
jsonschema==3.1.1
shapely==1.6.4.post2
regex==2019.8.19
boto3==1.9.192
AWSIoTPythonSDK==1.4.7
yolo34py-gpu
```

**Comment by madhawav** [comment]
Can you try moving numpy installation to a separate line in the docker file?
