### ISSUE TITLE
does it work with yolov4?

### ISSUE THREAD

**Issue by migueBC** [madhawav/YOLO3-4-Py#125]
I couldnt make it work with custom yolov4 files... the notebooks session crashes. 
name suggests also works on v4

**Comment by migueBC** [comment]
name suggests it runs yolov4, as well as v3, but it doesnt... just checked. thanks. closing

**Comment by madhawav** [comment]
Hi, the 4 stands for the word "for". I am sorry for the confusion. I did this work before YOLO v4 was released, so I didn't foresee this situation. 
YOLO v4 is not based on Darknet. So, it is not compatible with this wrapper.
