### ISSUE TITLE
Ubuntu 20.4 installation error

### ISSUE THREAD

**Issue by cedricve** [madhawav/YOLO3-4-Py#127]
I got this error when trying to build.

`
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE_CV=0 -I/usr/local/lib/python3.8/dist-packages/numpy/core/include -I/tmp/darknet/darknet-yolo34py-intergration-nocv/include -I/tmp/darknet/darknet-yolo34py-intergration-nocv/src -I/usr/include/python3.8 -c pydarknet.cpp -o build/temp.linux-x86_64-3.8/pydarknet.o 
x86_64-linux-gnu-gcc: error: : No such file or directory
`

**Comment by madhawav** [comment]
Hi
Please refer the solution here: https://github.com/madhawav/YOLO3-4-Py/issues/113#issuecomment-671949547

Let me know if it resolves.
