### ISSUE TITLE
FileNotFoundError: pkg-config, pkg-config

### ISSUE THREAD

**Issue by webmonki** [madhawav/YOLO3-4-Py#129]
I am trying to install YOLO3-4-Py on Ubuntu 18.04.5 LTS. Unfortunately pip3 install yolo34py throws the following error (After the 2021-02-27 fix): 

`FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config': 'pkg-config'`

**Complete traceback:**

` ERROR: Command errored out with exit status 1:
     command: /home/own/anaconda3/envs/product-recognition/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3pdwhgls/yolo34py_a31426b85fe64d21aa2a7369a9109134/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3pdwhgls/yolo34py_a31426b85fe64d21aa2a7369a9109134/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-plpnhhf4
         cwd: /tmp/pip-install-3pdwhgls/yolo34py_a31426b85fe64d21aa2a7369a9109134/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3pdwhgls/yolo34py_a31426b85fe64d21aa2a7369a9109134/setup.py", line 47, in <module>
        if USE_CV & (get_libs("opencv") == '' or get_cflags("opencv") == ''):
      File "/tmp/pip-install-3pdwhgls/yolo34py_a31426b85fe64d21aa2a7369a9109134/util.py", line 81, in get_libs
        proc = subprocess.Popen(shlex.split(command), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/home/lka/anaconda3/envs/product-recognition/lib/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/home/lka/anaconda3/envs/product-recognition/lib/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config': 'pkg-config'
`

**Comment by madhawav** [comment]
Hi,
Please install pkg-config using `sudo apt-get install -y pkg-config`. Alternatively, you can try installing from source code. It has more recent updates.
