### ISSUE TITLE
ImportError: No module named pydarknet

### ISSUE THREAD

**Issue by TaoFu-0204** [madhawav/YOLO3-4-Py#132]
I'm trying to run YOLO-3-4-Py on Ubuntu 18.04. 
I put a test image named `img1.png` in `~/YOLO-3-4-Py/demo/`, but after I got in `YOLO-3-4-Py` and ran `python demo/image_demo.py demo/img1.png`, python return ImportError to me.

Complete traceback:
Traceback (most recent call last):
  File "demo/image_demo.py", line 1, in <module>
    from pydarknet import Detector, Image
ImportError: No module named pydarknet

Even after I installed `darknet-py` by pip, this ImportError still be thrown to me. Can you help me please? Thanks.

**Comment by madhawav** [comment]
Hi, 
Please install yolo34py by following running `pip install yolo34py` or `pip install yolo34py-gpu`. Then, you should be able to run the demo.

**Comment by TaoFu-0204** [comment]
Hi,
I've tried to install it by `pip install yolo34py`, but after I installed yolo34py-0.2, it still keeps telling me `No module named pydarknet`.

**Comment by madhawav** [comment]
Hi,
Are you working inside a virtual environment? If so, is your pip configured to use the same environment?

To be sure, try installing yolo34py using the following command:
```bash
python -m pip install yolo34py
```

Also, you can run the pip install in verbose mode as follows. This gives detailed error messages.
```bash
python -m pip -v install yolo34py
```

**Comment by madhawav** [comment]
Closing the issue due to lack of response.

**Comment by Ajithkumarkk9** [comment]
> Hi, Please install yolo34py by running `pip install yolo34py` or `pip install yolo34py-gpu`. Then, you should be able to run the image_demo.py. Let me know if that doesn't work.
yess
