### ISSUE TITLE
Proxy issue in downloading https://github.com/madhawav/darknet while installing YOLO34PY using PIP

### ISSUE THREAD

**Issue by AjeetSingh02** [madhawav/YOLO3-4-Py#133]
Hey Madhawa,

I am trying to install your library (YOLO34PY) using PIP inside a proxy server. The PIP package is trying to download Darknet (https://github.com/madhawav/darknet) and build it. This build directly from GITHUB is not supported by the proxy server and hence it's blocking it. 

The security team upon looking at your darknet repo (which is getting downloaded) are asking the question about who will be maintaining this repo, since you have not made any changes from past 3 years.

So I was wondering can we use the original darknet (https://github.com/pjreddie/darknet) by changing the path in setup files.

Please help with this.

**Comment by madhawav** [comment]
Hi @AjeetSingh02 
You can use the original darknet repo by following the __installation from source__ instructions here:https://github.com/madhawav/YOLO3-4-Py#installation-from-source

Make a clone of the original darknet repo and update the environment variable DARKNET_HOME to point to it. Then, follow the instructions to build from the source.
