### ISSUE TITLE
crashes on colab using custom weights/config

### ISSUE THREAD

**Issue by simonm3** [madhawav/YOLO3-4-Py#134]
I have custom trained weights/config files for yolov3 tiny with relu. This works fine with darknet directly. However when I pass the same weights and config file to Detector colab crashes and restarts with no error message.

I can run your colab example fine.

**Comment by madhawav** [comment]
Hi @simonm3 
Probably the darknet embedded inside the library is different from the darknet version you trained the model on. Can you try installing from the source as described in the README?

Make sure to update the 'DARKNET_HOME' environment variable to point to the version of darknet you use.

**Comment by simonm3** [comment]
Thanks. In the end I fixed it somehow but not sure how so did not post the answer.
