### ISSUE TITLE
How to set which GPU to use？

### ISSUE THREAD

**Issue by kli-nlpr** [madhawav/YOLO3-4-Py#19]
Thank you very much!

**Comment by jantman** [comment]
I was also looking into this, but my really poor C knowledge doesn't make it easy.

It looks like the [darknet example script](https://github.com/pjreddie/darknet/blob/d3828827e70b293a3045a1eb80bfb4026095b87b/examples/darknet.c#L412-L423) both sets the [gpu_index int](https://github.com/pjreddie/darknet/blob/d3828827e70b293a3045a1eb80bfb4026095b87b/include/darknet.h#L9) and calls ``cuda_set_device()``. It appears that this can also be used to disable using the GPU even if the code was compiled for GPU support, by setting the gpu_index to -1

**Comment by madhawav** [comment]
@kli-nlpr The new merge request #25 has this feature implemented. Can you try it out and let me know whether it works as expected? Then I would merge it to master and do a new release. Unfortunately, I do not have multiple GPUs to test the code.

1) Uninstall the version you have installed right now (`pip uninstall yolo34py-gpu`)
2) Clone the code in merge request #25
3) Set environment variables GPU=1 and OPENCV=1.
4) Run `pip install .`
5) Use `pydarknet.set_cuda_device` to change the GPU.

@jantman Thank you for your support. The link you mentioned helped me!

**Comment by madhawav** [comment]
Hi @jantman, I believe setting the GPU to zero would make it use the Primary GPU. Why don't you use the version without GPU? (`pip install yolo34py` instead of `pip install yolo34py-gpu`).

**Comment by madhawav** [comment]
Option to select GPU is implemented with #25

**Comment by woojeonghoon** [comment]
have eight GPUs.

By the way, 'python3 video_demo' only uses the first GPU and nothing else

What should I do??
