### ISSUE TITLE
Tiny yolo

### ISSUE THREAD

**Issue by sachinruk** [madhawav/YOLO3-4-Py#20]
How can you modify the script to use tiny yolo weights instead? In the original it was: `./darknet detect cfg/yolov3-tiny.cfg yolov3-tiny.weights data/dog.jpg`

**Comment by madhawav** [comment]
Hi, you just have to change the way where you initiate the Detector. 

For example, you can get the code of image_demo.py and modify Detector initiation line like this

```python
net = Detector(bytes("PATH TO yolov3-tiny.cfg FILE", encoding="utf-8"), bytes("PATH TO yolov3-tiny.weights FILE", encoding="utf-8"), 0,
                   bytes("cfg/coco.data", encoding="utf-8"))```
