### ISSUE TITLE
Scores 

### ISSUE THREAD

**Issue by cadestian** [madhawav/YOLO3-4-Py#23]
Hi! I have 2 questions.

1) What does zero mean in this line?

    net = Detector(bytes("cfg/yolov3.cfg", encoding="utf-8"), bytes("weights/yolov3.weights", encoding="utf-8"), 0,
                   bytes("cfg/coco.data", encoding="utf-8"))

2) How I can only detect object with score>n (f.e. 0.7)

Thanks!

**Comment by madhawav** [comment]
1) The zero corresponds to the `clean` parameter of load_network method of darknet (https://github.com/pjreddie/darknet/blob/d3828827e70b293a3045a1eb80bfb4026095b87b/src/network.c). I am not aware of its actual purpose but it seems it's only used for training. This parameter is actually a boolean value. (Even though an integer is expected by darknet).

2) Do something like this.
```python
filtered_results = []
results = net.detect(dark_frame)
for result in results:
   if result[1] > 0.7:
      filtered_results.append(result)
```
Now, filtered_results has detections with score > 0.7.
