### ISSUE TITLE
gcc: error: : No such file or directory

### ISSUE THREAD

**Issue by teaddicted** [madhawav/YOLO3-4-Py#26]
Hey,

I successfully compiled it a few days ago but due to ubuntu issues I had to repair it and that removed this library, so now I'm trying to install it again. But now I'm getting this:

![ss](https://user-images.githubusercontent.com/26036961/43699860-e63058c6-9969-11e8-9bf6-11bd36878bae.png)

I've looked in the other issue as well and I also tried setting pkgconfig path but that didn't fix my issue. I tried installing the branch without opencv but same error occurred. When I try to install it through PyPi I get the same error. Can you please help me in figuring this out.

Thanks.

EDIT: Never mind. I didn't source the profile. Okay but now I'm getting a different error.

- When I compile with Pjreddie's Darknet:
![ss2](https://user-images.githubusercontent.com/26036961/43700688-fe470ae2-996c-11e8-8bda-699079a8ffcf.png)

- When I compile with AlexeyAB's Darknet:
![ss3](https://user-images.githubusercontent.com/26036961/43700708-109e4b10-996d-11e8-8701-5cb2e47d3585.png)

**Comment by teaddicted** [comment]
I can't figure out which path I haven't set as I've followed all the instructions in compiling darknet and this one.

**Comment by ohadlahav** [comment]
Hi,
I get the `x86_64-linux-gnu-gcc: error: : No such file or directory` error when trying to run docker example.

`building 'pydarknet' extension
creating build
creating build/temp.linux-x86_64-3.5
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE_CV=0 -I/usr/lib/python3/dist-packages/numpy/core/include -I/darknet/include -I/darknet/src -I/usr/include/python3.5m -c pydarknet.cpp -o build/temp.linux-x86_64-3.5/pydarknet.o 
x86_64-linux-gnu-gcc: error: : No such file or directory
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
The command '/bin/sh -c python3 setup.py build_ext --inplace' returned a non-zero code: 1
`

**Comment by madhawav** [comment]
Hi,
Can you try out the pip install and let me know it works?
`pip install yolo34py' or 'pip instal yolo34py-gpu'. 

Thanks

**Comment by suchotomas** [comment]
Hello, I have the same problem. 
- tried right now with pip install for gpu
![screenshot from 2018-08-08 09-52-28](https://user-images.githubusercontent.com/30759242/43823893-d38a12f6-9af0-11e8-99b4-939a62bf654e.png)

**Comment by madhawav** [comment]
@suchotomas It seems `nvcc` is not added to `PATH` environment variable. Do you have CUDA Toolkit installed? If so, can you add `nvcc` to `PATH` environment variable?  

nvcc is usually located at `/usr/local/cuda/bin64` so running `export PATH=$PATH:/usr/local/cuda/bin64` should solve the issue.

**Comment by ohadlahav** [comment]
@madhawav i'm getting the **x86_64-linux-gnu-gcc: error** when trying the Docker example which i what i'm aiming for.

**Comment by teaddicted** [comment]
I modified alexeyab's darknet fork to work with video/webcam/images in real time so it's all good now.

**Comment by suchotomas** [comment]
@madhawav sure, you're right - I didn't notice the nvcc error. Thanks man!

**Comment by lozuwa** [comment]
Hello, I am getting the same error. Though I have added nvc to the PATH.

![screenshot from 2018-08-14 15-44-08](https://user-images.githubusercontent.com/11334414/44114456-41faea3e-9fd9-11e8-9829-321df25eded3.png)

**Comment by madhawav** [comment]
@lozuwa, whats your os? Will look into this.

**Comment by madhawav** [comment]
@lozuwa  Can you provide the complete output of the terminal window? Maybe you can copy the text and paste here.

**Comment by lozuwa** [comment]
Hey, thanks for the reply. 

Requirement already satisfied: cython>=0.27 in /home/nvd/anaconda3/envs/tensorflow_10/lib/python3.6/site-packages (from yolo34py) (0.28.5)
Requirement already satisfied: requests in /home/nvd/anaconda3/envs/tensorflow_10/lib/python3.6/site-packages (from yolo34py) (2.19.1)
Requirement already satisfied: numpy in /home/nvd/anaconda3/envs/tensorflow_10/lib/python3.6/site-packages (from yolo34py) (1.14.5)
Requirement already satisfied: certifi>=2017.4.17 in /home/nvd/anaconda3/envs/tensorflow_10/lib/python3.6/site-packages (from requests->yolo34py) (2018.8.13)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /home/nvd/anaconda3/envs/tensorflow_10/lib/python3.6/site-packages (from requests->yolo34py) (1.23)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/nvd/anaconda3/envs/tensorflow_10/lib/python3.6/site-packages (from requests->yolo34py) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /home/nvd/anaconda3/envs/tensorflow_10/lib/python3.6/site-packages (from requests->yolo34py) (2.7)
Installing collected packages: yolo34py
  Running setup.py install for yolo34py ... error
    Complete output from command /home/nvd/anaconda3/envs/tensorflow_10/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-idmmzui8/yolo34py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-roke9bh2/install-record.txt --single-version-externally-managed --compile:
    INFO:root:Selected Darknet Branch: yolo34py-intergration-nogpu from Darknet Fork 'https://github.com/madhawav/darknet/'
    /home/nvd/anaconda3/envs/tensorflow_10/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /home/nvd/anaconda3/envs/tensorflow_10/lib/python3.6/site-packages/setuptools/dist.py:388: UserWarning: Normalizing '0.1.rc12' to '0.1rc12'
      normalized_version,
    running install
    running build
    INFO:root:Temp Path: /tmp/darknet
    INFO:root:Downloading darknet
    INFO:root:Extracting darknet
    INFO:root:Building darknet
    INFO:root:Darknet building successful
    INFO:root:Moving to /tmp/pip-install-idmmzui8/yolo34py/__libdarknet/libdarknet.so
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/__libdarknet
    copying __libdarknet/__init__.py -> build/lib.linux-x86_64-3.6/__libdarknet
    running egg_info
    writing yolo34py.egg-info/PKG-INFO
    writing dependency_links to yolo34py.egg-info/dependency_links.txt
    writing requirements to yolo34py.egg-info/requires.txt
    writing top-level names to yolo34py.egg-info/top_level.txt
    reading manifest file 'yolo34py.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'yolo34py.egg-info/SOURCES.txt'
    copying __libdarknet/libdarknet.so -> build/lib.linux-x86_64-3.6/__libdarknet
    running build_ext
    skipping 'pydarknet.cpp' Cython extension (up-to-date)
    building 'pydarknet' extension
    creating build/temp.linux-x86_64-3.6
    gcc -pthread -B /home/nvd/anaconda3/envs/tensorflow_10/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CV=0 -I/home/nvd/anaconda3/envs/tensorflow_10/lib/python3.6/site-packages/numpy/core/include -I/tmp/darknet/darknet-yolo34py-intergration-nogpu/include -I/tmp/darknet/darknet-yolo34py-intergration-nogpu/src -I/home/nvd/anaconda3/envs/tensorflow_10/include/python3.6m -c pydarknet.cpp -o build/temp.linux-x86_64-3.6/pydarknet.o
    gcc: error: : No such file or directory
    error: command 'gcc' failed with exit status 1

**Comment by ChangJongHyun** [comment]
Hi! I have same problem.

my environment is

- ubuntu 18.04
- tensorflow 1.8.0
- cuda 9.0 // cudnn 7.1.4
- check CUDA PATH environment variables.

below is my full error text.

(tensorflow-gpu) dksshddl@dksshddl-desktop:~$ pip install yolo34py-gpu
Collecting yolo34py-gpu
  Using cached https://files.pythonhosted.org/packages/dc/a3/12c668e54109c5469a8312d757b357dda0b2efc2150043b76b58f6ba75c3/yolo34py-gpu-0.1rc12.tar.gz
Requirement already satisfied: cython>=0.27 in ./anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages (from yolo34py-gpu) (0.28.5)
Requirement already satisfied: requests in ./anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages (from yolo34py-gpu) (2.19.1)
Requirement already satisfied: numpy in ./anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages (from yolo34py-gpu) (1.14.5)
Requirement already satisfied: idna<2.8,>=2.5 in ./anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages (from requests->yolo34py-gpu) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages (from requests->yolo34py-gpu) (3.0.4)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in ./anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages (from requests->yolo34py-gpu) (1.23)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages (from requests->yolo34py-gpu) (2018.8.13)
Building wheels for collected packages: yolo34py-gpu
  Running setup.py bdist_wheel for yolo34py-gpu ... error
  Complete output from command /home/dksshddl/anaconda3/envs/tensorflow-gpu/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-n941a4xz/yolo34py-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-w4b40y20 --python-tag cp36:
  INFO:root:Selected Darknet Branch: yolo34py-intergration-nocv from Darknet Fork 'https://github.com/madhawav/darknet/'
  /home/dksshddl/anaconda3/envs/tensorflow-gpu/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  /home/dksshddl/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/setuptools/dist.py:388: UserWarning: Normalizing '0.1.rc12' to '0.1rc12'
    normalized_version,
  running bdist_wheel
  running build
  INFO:root:Temp Path: /tmp/darknet
  INFO:root:Downloading darknet
  INFO:root:Extracting darknet
  INFO:root:Building darknet
  INFO:root:Darknet building successful
  INFO:root:Moving to /tmp/pip-install-n941a4xz/yolo34py-gpu/__libdarknet/libdarknet.so
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/__libdarknet
  copying __libdarknet/__init__.py -> build/lib.linux-x86_64-3.6/__libdarknet
  running egg_info
  writing yolo34py_gpu.egg-info/PKG-INFO
  writing dependency_links to yolo34py_gpu.egg-info/dependency_links.txt
  writing requirements to yolo34py_gpu.egg-info/requires.txt
  writing top-level names to yolo34py_gpu.egg-info/top_level.txt
  reading manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
  copying __libdarknet/libdarknet.so -> build/lib.linux-x86_64-3.6/__libdarknet
  running build_ext
  skipping 'pydarknet.cpp' Cython extension (up-to-date)
  building 'pydarknet' extension
  creating build/temp.linux-x86_64-3.6
  gcc -pthread -B /home/dksshddl/anaconda3/envs/tensorflow-gpu/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CV=0 -I/home/dksshddl/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/numpy/core/include -I/tmp/darknet/darknet-yolo34py-intergration-nocv/include -I/tmp/darknet/darknet-yolo34py-intergration-nocv/src -I/home/dksshddl/anaconda3/envs/tensorflow-gpu/include/python3.6m -c pydarknet.cpp -o build/temp.linux-x86_64-3.6/pydarknet.o
  gcc: error: : No such file or directory
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for yolo34py-gpu
  Running setup.py clean for yolo34py-gpu
Failed to build yolo34py-gpu
Installing collected packages: yolo34py-gpu
  Running setup.py install for yolo34py-gpu ... error
    Complete output from command /home/dksshddl/anaconda3/envs/tensorflow-gpu/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-n941a4xz/yolo34py-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-arh3yo0i/install-record.txt --single-version-externally-managed --compile:
    INFO:root:Selected Darknet Branch: yolo34py-intergration-nocv from Darknet Fork 'https://github.com/madhawav/darknet/'
    /home/dksshddl/anaconda3/envs/tensorflow-gpu/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /home/dksshddl/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/setuptools/dist.py:388: UserWarning: Normalizing '0.1.rc12' to '0.1rc12'
      normalized_version,
    running install
    running build
    INFO:root:Temp Path: /tmp/darknet
    INFO:root:Downloading darknet
    INFO:root:Extracting darknet
    INFO:root:Building darknet
    INFO:root:Darknet building successful
    INFO:root:Moving to /tmp/pip-install-n941a4xz/yolo34py-gpu/__libdarknet/libdarknet.so
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/__libdarknet
    copying __libdarknet/__init__.py -> build/lib.linux-x86_64-3.6/__libdarknet
    running egg_info
    writing yolo34py_gpu.egg-info/PKG-INFO
    writing dependency_links to yolo34py_gpu.egg-info/dependency_links.txt
    writing requirements to yolo34py_gpu.egg-info/requires.txt
    writing top-level names to yolo34py_gpu.egg-info/top_level.txt
    reading manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'pydarknet.cpp'
    writing manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
    copying __libdarknet/libdarknet.so -> build/lib.linux-x86_64-3.6/__libdarknet
    running build_ext
    cythoning pydarknet.pyx to pydarknet.cpp
    building 'pydarknet' extension
    creating build/temp.linux-x86_64-3.6
    gcc -pthread -B /home/dksshddl/anaconda3/envs/tensorflow-gpu/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CV=0 -I/home/dksshddl/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/numpy/core/include -I/tmp/darknet/darknet-yolo34py-intergration-nocv/include -I/tmp/darknet/darknet-yolo34py-intergration-nocv/src -I/home/dksshddl/anaconda3/envs/tensorflow-gpu/include/python3.6m -c pydarknet.cpp -o build/temp.linux-x86_64-3.6/pydarknet.o
    gcc: error: : No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/dksshddl/anaconda3/envs/tensorflow-gpu/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-n941a4xz/yolo34py-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-arh3yo0i/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-n941a4xz/yolo34py-gpu/

**Comment by madhawav** [comment]
@lozuwa  and @ChangJongHyun, the error your getting is strange because gcc is trying to compile a file with blank name. GCC reports missing files using the format `gcc: error: [file_name] : No such file or directory` and in your case, the [file_name] is blank. 

1) Can you obtain a fresh clone on a new directory and re-run the setup script? Maybe some unnecessary files are left from previously failed installation attempts. 
2) Also you can try `python setup.py clean` option and afterwards run installation. 
3) Also, after a failed installation, can you find pydarknet.cpp created in the source directory? If it is their, delete it and re-run the setup script.

**Comment by lozuwa** [comment]
Hello @madhawav thanks for your responses. I got it fixed with the python setup.py clean.

**Comment by madhawav** [comment]
That's great! Thank you for stating the solution that worked!

**Comment by hsuRush** [comment]
@teaddicted  What did you modified in Alexeyab's darknet ?

**Comment by teaddicted** [comment]
@hsuRush I just changed the darknet.py file according to my needs. It's already given in the fork.

**Comment by hsuRush** [comment]
@teaddicted  There's an error occurred when I compile with  Alexeyab's darknet.
` bridge.h:15:21: fatal error: darknet.h: No such file or directory`

![darknet](https://user-images.githubusercontent.com/22855741/44942434-3a2cdc00-ade3-11e8-8f0a-740738e206d2.PNG)
and when I comment out the `#include <darknet.h>` in `bridge.h` , there're some conflicting declaration errors.

**Comment by reisman234** [comment]
> 
> 
> @lozuwa and @ChangJongHyun, the error your getting is strange because gcc is trying to compile a file with blank name. GCC reports missing files using the format `gcc: error: [file_name] : No such file or directory` and in your case, the [file_name] is blank.
> 
>     1. Can you obtain a fresh clone on a new directory and re-run the setup script? Maybe some unnecessary files are left from previously failed installation attempts.
> 
>     2. Also you can try `python setup.py clean` option and afterwards run installation.
> 
>     3. Also, after a failed installation, can you find pydarknet.cpp created in the source directory? If it is their, delete it and re-run the setup script.


Hi, 
I having trouble to create a docker image, because of this error (gcc: error: : No such file or directory
).  

I changed the existing Dockerfile to use my own docker Image as a base.  My Image uses as base the nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04 and extends it with an jupyter notebook, so in this image is a conda (anaconda) environment. 

Now when i'm run the run.sh script it builds the new image until it reaches the step 
`RUN python3 setup.py build_ext --inplace`

after that it throws that error

`Step 34/38 : RUN conda install pkgconfig cython
 ---> Using cache
 ---> 39ff80ae70fe
Step 35/38 : RUN python3 setup.py build_ext --inplace
 ---> Running in b76b856c73fd
INFO:root:DARKNET_HOME is set: /home/ml2_user/work/darknet
running build_ext
/opt/conda/lib/python3.6/site-packages/setuptools/dist.py:470: UserWarning: Normalizing '0.1.rc13' to '0.1rc13'
  normalized_version,
INFO:root:For inplace compilations, target location is set to root
INFO:root:Copying libdarknet.so from /home/ml2_user/work/darknet
cythoning pydarknet.pyx to pydarknet.cpp
building 'pydarknet' extension
creating build
creating build/temp.linux-x86_64-3.6
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m64 -fPIC -m64 -fPIC -fPIC -DUSE_GPU=0 -DUSE_CV=0 -I/opt/conda/lib/python3.6/site-packages/numpy/core/include -I/home/ml2_user/work/darknet/include -I/home/ml2_user/work/darknet/src -I/opt/conda/include/python3.6m -c pydarknet.cpp -o build/temp.linux-x86_64-3.6/pydarknet.o
gcc: error: : No such file or directory
/opt/conda/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/ml2_user/work/YOLO3-4-Py/pydarknet.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
error: command 'gcc' failed with exit status 1
The command '/bin/sh -c python3 setup.py build_ext --inplace' returned a non-zero code: 1`
