### ISSUE TITLE
How can I count the detected objects

### ISSUE THREAD

**Issue by matheusfpinto** [madhawav/YOLO3-4-Py#31]
Hello, I'm searching how to count detected objects that cross a ROI Line (Line of interest). Have anyone do that with this Wraped YOLO application? Thanks!

**Comment by madhawav** [comment]
Hi, 
What you propose is a very specific application of API. Most probably you will have to develop the solution on your own e or adapt an existing project you may find online. 

Anyhow, I am closing this issue as it is more than two weeks old without a response. Also, it neither explains a feature addition nor a bug of yolo34py.

Cheers!
