### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by pdavis39** [madhawav/YOLO3-4-Py#33]
Appreciate the python wrapper, nice work.

I am curious if there is a configuration that would improve performance.

When I invoke ./dark-net detect demo /foo/video.mp4 my setup gets around ~20 fps using yolov3-tiny.cfg and yolov3-tiny.weights on a Jetson TX2.

when I run python3 video_demo.py with the same parameters and same video it appears to be in the ~5 fps. Below is the setup 

I have tried with both python3.5 and python3.6, python3.6 appears to be a bit faster. 
...
net = Detector(bytes("cfg/yolov3-tiny.cfg", encoding="utf-8"), bytes("weights/yolov3-tiny.weights", encoding="utf-8"), 0,
bytes("cfg/coco.data", encoding="utf-8"))
...

Any thoughts why? Thanks in advance for your support.

**Comment by hj3yoo** [comment]
I've also tried using video_demo.py, but it's not using my GPU for it:

`edmond@edmond-OptiPlex-3020:~/Desktop/yolo_py_$ nvidia-smi
Thu Sep 13 14:28:24 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54                 Driver Version: 396.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960     Off  | 00000000:01:00.0  On |                  N/A |
| 23%   51C    P0    29W / 130W |    641MiB /  4035MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1157      G   /usr/lib/xorg/Xorg                            26MiB |
|    0      1193      G   /usr/bin/gnome-shell                          49MiB |
|    0      1530      G   /usr/lib/xorg/Xorg                           275MiB |
|    0      1644      G   /usr/bin/gnome-shell                         152MiB |
|    0      2308      G   ...uest-channel-token=15699809938454097634   114MiB |
+-----------------------------------------------------------------------------+
`

As a result, the processing speed was less than 1fps, and wasn't even correct - it didn't generate identical detection result compared to when I used another [C-based darknet repo](https://github.com/AlexeyAB/darknet)

`Total Time: 1.020754337310791 : 0.20415086746215821
Total Time: 1.0239546298980713 : 0.36811161994934083
Total Time: 1.0046367645263672 : 0.4954166488647461
Total Time: 1.0040676593780518 : 0.5971468509674073
Total Time: 1.00557279586792 : 0.6788320399475098
Total Time: 1.0664269924163818 : 0.7563510304412844
Total Time: 1.0445141792297363 : 0.8139836601989748
Total Time: 1.0592858791351318 : 0.8630441039862062
Total Time: 1.0077087879180908 : 0.8919770407725832
Total Time: 1.0038435459136963 : 0.9143503418008059
Total Time: 1.0115818977355957 : 0.9337966529877638
Total Time: 1.0331337451934814 : 0.9536640714289074
Total Time: 1.0150625705718994 : 0.9659437712575059
Total Time: 1.0100688934326172 : 0.9747687956925282
Total Time: 0.9993100166320801 : 0.9796770398804386
Total Time: 0.9945197105407715 : 0.9826455740125053
Total Time: 0.9960606098175049 : 0.9853285811735053
Total Time: 1.007739543914795 : 0.9898107737217633
Total Time: 0.9996283054351807 : 0.9917742800644468
Total Time: 0.9996798038482666 : 0.9933553848212109
Total Time: 1.042731523513794 : 1.0032306125597277
Total Time: 1.006467580795288 : 1.0038780062068398
Total Time: 1.0151450634002686 : 1.0061314176455256
Total Time: 1.0330297946929932 : 1.011511093055019
Total Time: 1.0217530727386475 : 1.0135594889917448
Total Time: 1.0140748023986816 : 1.0136625516731321
Total Time: 1.0175750255584717 : 1.0144450464502002
Total Time: 1.0418338775634766 : 1.0199228126728554
Total Time: 1.042085886001587 : 1.0243554273386017
Total Time: 1.0340359210968018 : 1.0262915260902419
Total Time: 1.0960707664489746 : 1.0402473741619884
Total Time: 1.0259060859680176 : 1.0373791165231943
Total Time: 1.0076789855957031 : 1.0314390903376962
Total Time: 1.0073304176330566 : 1.0266173557967684
Total Time: 1.0638904571533203 : 1.0340719760680788
Total Time: 1.0071144104003906 : 1.0286804629345412
Total Time: 1.0388805866241455 : 1.030720487672462
Total Time: 1.0053002834320068 : 1.025636446824371
Total Time: 0.9988765716552734 : 1.0202844717905517
Total Time: 1.0000808238983154 : 1.0162437422121045
Total Time: 1.0091533660888672 : 1.0148256669874571
Total Time: 1.063516616821289 : 1.0245638569542237
Total Time: 1.0315601825714111 : 1.0259631220776613
Total Time: 0.9988641738891602 : 1.020543332439961
Total Time: 1.002253532409668 : 1.0168853724339024
Total Time: 0.9962501525878906 : 1.0127583284647002
Total Time: 1.052403450012207 : 1.0206873527742015
Total Time: 1.123659610748291 : 1.0412818043690195
Total Time: 1.023949384689331 : 1.037815320433082
Total Time: 1.2068777084350586 : 1.0716277980334774
Total Time: 1.0803277492523193 : 1.0733677882772459
Total Time: 1.16245698928833 : 1.0911856284794628
Total Time: 1.1067988872528076 : 1.0943082802341317
Total Time: 1.0875051021575928 : 1.092947644618824
Total Time: 1.1199381351470947 : 1.0983457427244783
Total Time: 1.0975828170776367 : 1.09819315759511
Total Time: 1.1414506435394287 : 1.1068446547839739
Total Time: 1.0815680027008057 : 1.1017893243673402
Total Time: 1.0899229049682617 : 1.0994160404875246
Total Time: 1.0701749324798584 : 1.0935678188859914
Total Time: 1.0667169094085693 : 1.088197636990507
Total Time: 1.0523920059204102 : 1.0810365107764879
Total Time: 1.100783109664917 : 1.0849858305541737
Total Time: 1.114901065826416 : 1.0909688776086222`

**Comment by madhawav** [comment]
Hi, did you install yolo34py with GPU enabled as explained [here](https://github.com/madhawav/YOLO3-4-Py#installation-from-source)? You need to set some environment variables as explained above to enable GPU acceleration. 

On the other hand, you can directly install the GPU version using the pip package.
`pip install yolo34py-gpu`

**Comment by abhigarg** [comment]
Hi, you guys do not need to use any separate wrapper for Darknet-Yolo as the python script is already provided which uses the build from original darknet library. It will give same performance as the original darknet build. Refer to my [repo](https://github.com/abhigarg/darknet-yolo-python) for more details
