### ISSUE TITLE
ImportError (library not loaded) at runtime

### ISSUE THREAD

**Issue by zulufoxtrot** [madhawav/YOLO3-4-Py#34]
I get this error at runtime:

> Traceback (most recent call last):
>   File "/Users/zulu/docs/projets/dev/python/yolo-computer-vision/YOLO3-4-Py/video_demo.py", line 3, in \<module\>
>     from pydarknet import Detector, Image
> ImportError: dlopen(/usr/local/lib/python3.7/site-packages/pydarknet.cpython-37m-darwin.so, 2): Library not loaded: libdarknet.so
>   Referenced from: /usr/local/lib/python3.7/site-packages/pydarknet.cpython-37m-darwin.so
>   Reason: image not found

### Environment
MacOS 10.13.5
Python 3.7
CUDA SDK 9.2 (note: I do have a nvidia GPU)
OpenCV 3.4.2

### Installation
I installed from source to get OpenCV support.
Followed these steps:
pip3 install numpy
brew install opencv
export CUDA_HOME=/usr/local/cuda
export PATH=${CUDA_HOME}/bin:${PATH}
export LD_LIBRARY_PATH=${CUDA_HOME}/lib:$LD_LIBRARY_PATH
export GPU=1
export OPENCV=1
git clone https://github.com/madhawav/YOLO3-4-Py.git
cd YOLO3-4-Py/
pip3 install . --verbose

This is the full output of the install process:
[Output](https://paste.ofcode.org/MsQWXaWVtdQc6hNA2AmfjD
)

**Comment by zulufoxtrot** [comment]
Found an explanation:
https://stackoverflow.com/questions/19776571/error-dlopen-library-not-loaded-reason-image-not-found

I'm not sure I understand the issue at hand, but I investigated and found a workaround:

First let's see where what _pydarknet.cpython-37m-darwin.so_ is looking for:

> otool -L /usr/local/lib/python3.7/site-packages/pydarknet.cpython-37m-darwin.so
> /usr/local/lib/python3.7/site-packages/pydarknet.cpython-37m-darwin.so:
> 	libdarknet.so (compatibility version 0.0.0, current version 0.0.0)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
> 	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)

It looks like libdarknet.so is referenced with a _relative_ path.
Its _absolute_ path is /usr/local/lib/python3.7/site-packages/__libdarknet/libdarknet.so

A workaround is to copy libdarknet.so to the current working directory.

But then, another error arises:

> Traceback (most recent call last):
>   File "/Users/zulu/docs/projets/dev/python/yolo-computer-vision/YOLO3-4-Py/video_demo.py", line 3, in <module>
>     from pydarknet import Detector, Image
> ImportError: dlopen(/usr/local/lib/python3.7/site-packages/pydarknet.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libcudart.9.2.dylib
>   Referenced from: /Users/zulu/docs/projets/dev/python/yolo-computer-vision/YOLO3-4-Py/libdarknet.so
>   Reason: image not found

Let's run otool again:

> otool -L libdarknet.so
> libdarknet.so:
> 	libdarknet.so (compatibility version 0.0.0, current version 0.0.0)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
> 	/usr/local/opt/opencv/lib/libopencv_stitching.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_superres.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_videostab.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_aruco.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_bgsegm.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_bioinspired.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_ccalib.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_dnn_objdetect.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_dpm.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_face.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_photo.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_fuzzy.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_hfs.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_img_hash.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_line_descriptor.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_optflow.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_reg.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_rgbd.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_saliency.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_stereo.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_structured_light.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_phase_unwrapping.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_surface_matching.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_tracking.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_datasets.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_dnn.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_plot.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_xfeatures2d.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_shape.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_video.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_ml.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_ximgproc.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_calib3d.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_features2d.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_highgui.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_videoio.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_flann.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_xobjdetect.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_imgcodecs.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_objdetect.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_xphoto.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_imgproc.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/opt/opencv/lib/libopencv_core.3.4.dylib (compatibility version 3.4.0, current version 3.4.2)
> 	/usr/local/cuda/lib/libcuda.dylib (compatibility version 1.1.0, current version 9.2.64)
> 	**@rpath/libcudart.9.2.dylib** (compatibility version 0.0.0, current version 9.2.148)
> 	**@rpath/libcublas.9.2.dylib** (compatibility version 0.0.0, current version 9.2.148)
> 	**@rpath/libcurand.9.2.dylib** (compatibility version 0.0.0, current version 9.2.148)
> 	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)

So this is the same issue as before, except this time the paths are absolute.

I don't know how @rpath works, but on my system the 3 dylibs are in Developer/NVIDIA/CUDA-9.2/lib/.

No big deal, just use **install_name_tool** to change the paths:

install_name_tool -change @rpath/libcudart.9.2.dylib /Developer/NVIDIA/CUDA-9.2/lib/libcudart.9.2.dylib libdarknet.so
install_name_tool -change @rpath/libcublas.9.2.dylib /Developer/NVIDIA/CUDA-9.2/lib/libcublas.9.2.dylib
install_name_tool -change @rpath/libcurand.9.2.dylib /Developer/NVIDIA/CUDA-9.2/lib/libcurand.9.2.dylib

After doing this, the python script runs fine! 

I think something has to be changed in the install script to fix this.

**Comment by madhawav** [comment]
Hi @zulufoxtrot,  Unfortunately, yolo34py do not officially support MacOS. I believe that is why API failed to link with libdarknet.so automatically as intended. 

Anyhow, I am glad you managed to find a solution. Would you be able to share the changes you made as a pull request? Then we can maintain a separate branch for Mac OS. (Unfortunately, I will not be able to contribute to the MacOS branch since I do not have a Mac)
Cheers!
