### ISSUE TITLE
Yolo9000

### ISSUE THREAD

**Issue by spirosperos** [madhawav/YOLO3-4-Py#36]
How could you compile this so it detects 9000 different classes?
EDIT:
I managed to do it, by downloading appropriate weights and labels. The thing is, when I run nvidia-smi:

![image](https://user-images.githubusercontent.com/30575489/46404329-1ec83000-c705-11e8-96b2-932a3edfd931.png)
I see that it uses only ~1400 out of 8110MB of GPU memory. The version with only 80 classes uses almost the whole memory. Do you know if this is normal, and if not how can it be solved?
Thanks

**Comment by madhawav** [comment]
The amount of memory used depends on the complexity of the neural network architecture. The number of classes alone cannot be used to comment on memory requirement.
