### ISSUE TITLE
AWS Lambda Implementation

### ISSUE THREAD

**Issue by jsclose** [madhawav/YOLO3-4-Py#38]
Have you / anyone been able to implement this in an AWS lambda, such that when a new photo is uploaded, a lambda would run the yolo on the new image?

**Comment by madhawav** [comment]
Hi @jsclose did you find such an implementation?

**Comment by jsclose** [comment]
A project like this is similar https://github.com/fmacrae/YOLO-on-Lambda. However, I realized that running this in a aws lambda isn't the best use case of a lambda. I was trying to process a video and the time duration / space of a lambda isn't sufficient. A single photo analysis could work for this. I am moving my architecture to use a lambda to push a darknet running job to a queue that an EC2 instance will pull and then process. Need to find tutorials on how to set up on EC2 instance
