### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by cspoh** [madhawav/YOLO3-4-Py#4]
Hi, does the wrapper support training?

Thanks

**Comment by madhawav** [comment]
Hi, currently no. But it is a possible future addition since darknet supports training. I would look into that in the future.
Any contributions from the community are mostly welcome 😄

**Comment by madhawav** [comment]
I have looked into this and I could not convince myself why one should use the Python wrapper just to train yolo3 model without making any network modifications. This problem would eventually become similar to designing a new Python machine learning framework specialized in Darknet implementation of Yolo3.
