### ISSUE TITLE
ImportError: libdarknet.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by DRACOyu** [madhawav/YOLO3-4-Py#40]
ImportError: libdarknet.so: cannot open shared object file: No such file or directory

**Comment by DRACOyu** [comment]
how to solve it

**Comment by madhawav** [comment]
Hi,
Can you share more information such as 
1) Name of the operating system and version
2) Version of python
3) Version of Cython

Also, did you get any errors during installation?

**Comment by rohitpattnaik** [comment]
Hi,

I used yolo earlier with some success but now my import throws this same error.
Could you please help on this:

1. OS : Ubuntu 16.04
2. Python: Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux

No Errors during pip install.

Environment : 
(yolo_test) rohit@rohit-GL503VM:~/PycharmProjects/MyTest$ conda list
# packages in environment at /home/rohit/anaconda3/envs/yolo_sld_test:
#
# Name                    Version                   Build  Channel
absl-py                   0.6.1                    py36_0    anaconda
astor                     0.7.1                    py36_0    anaconda
blas                      1.0                         mkl  
bleach                    1.5.0                    py36_0  
boost                     1.59.0                   py36_0    menpo
bzip2                     1.0.6                h14c3975_5  
c-ares                    1.15.0               h7b6447c_1    anaconda
ca-certificates           2018.03.07                    0    anaconda
certifi                   2018.10.15               py36_0    anaconda
chardet                   3.0.4                     <pip>
cloudpickle               0.6.1                     <pip>
cudatoolkit               9.0                  h13b8566_0  
cudnn                     7.1.2                 cuda9.0_0  
cupti                     9.0.176                       0  
cycler                    0.10.0                    <pip>
Cython                    0.29                      <pip>
dask                      0.20.2                    <pip>
decorator                 4.3.0                     <pip>
dlib                      19.16.0                   <pip>
gast                      0.2.0                    py36_0    anaconda
giflib                    5.1.4                h470a237_1    conda-forge
grpcio                    1.16.1           py36hf8bcb03_1  
h5py                      2.8.0            py36h989c5e5_3    anaconda
hdf5                      1.10.2               hba1933b_1    anaconda
html5lib                  0.9999999                py36_0  
idna                      2.7                       <pip>
intel-openmp              2019.0                      118  
jpeg                      9b                   h024ee3a_2  
json                      0.1.1                         0    jmcmurray
Keras                     2.2.4                     <pip>
keras-applications        1.0.6                    py36_0    anaconda
keras-preprocessing       1.0.5                    py36_0    anaconda
kiwisolver                1.0.1                     <pip>
leptonica                 1.76.0               h1ccaaf6_4    conda-forge
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.35               hbc83047_0  
libprotobuf               3.6.1                hd408876_0    anaconda
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.9                he6b73bb_1    conda-forge
libwebp                   0.5.2                         7    conda-forge
markdown                  3.0.1                    py36_0    anaconda
matplotlib                3.0.2                     <pip>
mkl                       2019.0                      118  
mkl_fft                   1.0.6            py36h7dd41cf_0    anaconda
mkl_random                1.0.1            py36h4414c95_1    anaconda
ncurses                   6.1                  hf484d3e_0  
networkx                  2.2                       <pip>
numpy                     1.14.5                    <pip>
numpy                     1.15.4           py36h1d66e8a_0    anaconda
numpy-base                1.15.4           py36h81de0dd_0    anaconda
opencv-python             3.4.0.12                  <pip>
openjpeg                  2.3.0                h0e734dc_3    conda-forge
openssl                   1.1.1                h7b6447c_0    anaconda
pandas                    0.23.4                    <pip>
Pillow                    5.3.0                     <pip>
pip                       18.1                     py36_0    anaconda
protobuf                  3.6.1            py36he6710b0_0    anaconda
pyparsing                 2.3.0                     <pip>
pytesseract               0.2.5                     <pip>
python                    3.6.7                h0371630_0  
python-dateutil           2.7.5                     <pip>
pytz                      2018.7                    <pip>
PyWavelets                1.0.1                     <pip>
PyYAML                    3.13                      <pip>
qutil                     3.2.1                         6    jmcmurray
readline                  7.0                  h7b6447c_5  
requests                  2.20.1                    <pip>
scikit-image              0.14.1                    <pip>
scikit-learn              0.20.0                    <pip>
scipy                     1.1.0            py36hfa4b5c9_1    anaconda
scipy                     1.1.0                     <pip>
setuptools                40.5.0                   py36_0  
six                       1.11.0                    <pip>
six                       1.11.0                   py36_1    anaconda
sklearn                   0.0                       <pip>
sqlite                    3.25.3               h7b6447c_0  
tensorboard               1.7.0            py36hf484d3e_1  
tensorflow-gpu            1.7.0                         0  
tensorflow-gpu-base       1.7.0            py36hcdda91b_1  
termcolor                 1.1.0                    py36_1    anaconda
tk                        8.6.8                hbc83047_0  
toolz                     0.9.0                     <pip>
tqdm                      4.28.1                    <pip>
urllib3                   1.24.1                    <pip>
werkzeug                  0.14.1                   py36_0    anaconda
wheel                     0.32.2                   py36_0  
xz                        5.2.4                h14c3975_4  
yolo34py                  0.1rc12                   <pip>
zlib                      1.2.11               ha838bed_2

**Comment by madhawav** [comment]
Hi,
Can you do a locate to libdarknet.so and see whether it exists somewhere? 
`locate libdarknet.so`

That path should be added to your LD_LIBRARY_PATH.

**Comment by agusgun** [comment]
You can also use symlink to link the libdarknet.so

**Comment by madhawav** [comment]
Closing issue due to two weeks inactivity. Re-open if the problem still exists.

**Comment by qzho** [comment]
Hi,

I encountered the same error for yolo34py-gpu. I am running with 
1. Ubuntu 18.04
2. Python 3.6.8 :: Anaconda, Inc.
3. Cuda 10.1

No error showed during pip install. The libdarknet.so exists. I tried adding the path to LD_LIBRARY_PATH. Not working.

I also tried pip install yolo34py, which worked perfectly well.

Any suggestion would be much appreciated.
