### ISSUE TITLE
importerror pydarknet

### ISSUE THREAD

**Issue by tf401** [madhawav/YOLO3-4-Py#41]
Problem: Cannot import pydarknet
Mac OS 10.13.4
Python 3.5.0

Installation by instruction
************************************************************************************************
`$ pip install yolo34py`
Collecting yolo34py
Requirement already satisfied: requests in /anaconda3/envs/sleip/lib/python3.5/site-packages/requests-2.19.1-py3.5.egg (from yolo34py) (2.19.1)
Requirement already satisfied: numpy in /anaconda3/envs/sleip/lib/python3.5/site-packages (from yolo34py) (1.15.2)
Requirement already satisfied: cython>=0.27 in /anaconda3/envs/sleip/lib/python3.5/site-packages (from yolo34py) (0.28.5)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/envs/sleip/lib/python3.5/site-packages (from requests->yolo34py) (2018.8.24)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/envs/sleip/lib/python3.5/site-packages/chardet-3.0.4-py3.5.egg (from requests->yolo34py) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /anaconda3/envs/sleip/lib/python3.5/site-packages/idna-2.7-py3.5.egg (from requests->yolo34py) (2.7)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /anaconda3/envs/sleip/lib/python3.5/site-packages/urllib3-1.23-py3.5.egg (from requests->yolo34py) (1.23)
Installing collected packages: yolo34py
Successfully installed yolo34py-0.1rc12

************************************************************************************************

Python
************************************************************************************************
`from pydarknet import Detector, Image`

`ImportError Traceback (most recent call last)
<ipython-input-2-16743eae4a3b> in <module>
----> 1 from pydarknet import Detector, Image`

`ImportError: dlopen(/anaconda3/envs/sleip/lib/python3.5/site-packages/pydarknet.cpython-35m-darwin.so, 2): Library not loaded: libdarknet.so
  Referenced from: /anaconda3/envs/sleip/lib/python3.5/site-packages/pydarknet.cpython-35m-darwin.so
  Reason: image not found`
************************************************************************************************

Envirionment (sorry for formatting)
************************************************************************************************
$ conda list
packages in environment at /anaconda3/envs/sleip:

Name                    Version                   Build  Channel
absl-py                   0.5.0                     <pip>
appnope                   0.1.0                     <pip>
argparse                  1.4.0                     <pip>
astor                     0.7.1                     <pip>
backcall                  0.1.0                     <pip>
ca-certificates           2018.03.07                    0  
certifi                   2018.8.24                py35_1  
chardet                   3.0.4                     <pip>
cloudpickle               0.6.1                     <pip>
cycler                    0.10.0                    <pip>
Cython                    0.28.5                    <pip>
dask                      0.19.4                    <pip>
decorator                 4.3.0                     <pip>
dill                      0.2.7.1                   <pip>
fire                      0.1.3                     <pip>
gast                      0.2.0                     <pip>
grpcio                    1.15.0                    <pip>
h5py                      2.8.0                     <pip>
idna                      2.7                       <pip>
ipykernel                 5.1.0                     <pip>
ipython                   7.0.1                     <pip>
ipython-genutils          0.2.0                     <pip>
jedi                      0.13.1                    <pip>
jupyter-client            5.2.3                     <pip>
jupyter-core              4.4.0                     <pip>
Keras-Applications        1.0.6                     <pip>
Keras-Preprocessing       1.0.5                     <pip>
kiwisolver                1.0.1                     <pip>
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1.20170329         hb402a30_2  
Markdown                  3.0.1                     <pip>
matplotlib                3.0.0                     <pip>
msgpack                   0.5.6                     <pip>
msgpack-numpy             0.4.4.1                   <pip>
ncurses                   6.1                  h0a44026_0  
networkx                  2.2                       <pip>
numpy                     1.15.2                    <pip>
opencv-python             3.4.0.14                  <pip>
openssl                   1.0.2p               h1de35cc_0  
parso                     0.3.1                     <pip>
pexpect                   4.6.0                     <pip>
pickleshare               0.7.5                     <pip>
Pillow                    5.3.0                     <pip>
pip                       10.0.1                   py35_0  
prompt-toolkit            2.0.5                     <pip>
protobuf                  3.6.1                     <pip>
psutil                    5.4.7                     <pip>
ptyprocess                0.6.0                     <pip>
pyarrow                   0.11.0                    <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.2                     <pip>
python                    3.5.0                         1  
python-dateutil           2.7.3                     <pip>
PyWavelets                1.0.1                     <pip>
pyzmq                     17.1.2                    <pip>
readline                  6.2                           2  
requests                  2.19.1                    <pip>
scikit-image              0.14.1                    <pip>
scipy                     1.1.0                     <pip>
setuptools                39.1.0                    <pip>
setuptools                40.2.0                   py35_0  
simplegeneric             0.8.1                     <pip>
six                       1.11.0                    <pip>
slidingwindow             0.0.13                    <pip>
sqlite                    3.25.2               ha441bb4_0  
tensorboard               1.11.0                    <pip>
tensorflow                1.11.0                    <pip>
tensorpack                0.8.9                     <pip>
termcolor                 1.1.0                     <pip>
tf-pose                   0.1.1                     <pip>
tk                        8.5.18                        0  
toolz                     0.9.0                     <pip>
tornado                   5.1.1                     <pip>
tqdm                      4.26.0                    <pip>
traitlets                 4.3.2                     <pip>
urllib3                   1.23                      <pip>
wcwidth                   0.1.7                     <pip>
Werkzeug                  0.14.1                    <pip>
wheel                     0.31.1                   py35_0  
xz                        5.0.5                         1  
yolo34py                  0.1rc12                   <pip>
zlib                      1.2.11               hf3cbc9b_2 
************************************************************************************************

**Comment by madhawav** [comment]
@tf401 Unfortunately we don't support Mac OS Operating system.
Cheers!
