### ISSUE TITLE
yolo34py-gpu

### ISSUE THREAD

**Issue by kenrubiooo** [madhawav/YOLO3-4-Py#43]
Hi

I am having a problem with yolo34py-gpu. I wanted to process a video using the GPU version. However, when I run the algorithm, it says there:

layer     filters    size              input                output
    0 CUDA Error: unknown error
python: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)

What I did is to install yolo34py. So, what I have right now is the cpu and the gpu versions. What happens is that when I run the algorithm, it works fine but very slow. This is due to the cpu version.  Why is that the GPU version producing such error as shown above? Thank you!

**Comment by madhawav** [comment]
Hi,
The issue comes from the darknet side. I found [this thread](https://github.com/pjreddie/darknet/issues/98) on darknet repo which discusses the same issue. 

It suggests that this issue is due to the lack of sufficient GPU memory.
Kindly refer it.
