### ISSUE TITLE
Removing time.time() messes up bounding boxes

### ISSUE THREAD

**Issue by aj-ames** [madhawav/YOLO3-4-Py#46]
I came across this mind boggling issue. For my own yolov3 model for a custom dataset (which works absolutely fine with darknet) the bounding boxes are not plotted in place of the object when I move the object around. (Especially when the object is around the coordinates x <= 300 y <= 100 for my webcam where the opecv frame has shape (480, 640, 3) )
Your script works absolutely fine when I dont comment out the start_time = time.time() statement. Please help. This error is disturbing cause I dont understand. 

I used your webcam example:

import time

    from pydarknet import Detector, Image
    import cv2

    if __name__ == "__main__":
    # Optional statement to configure preferred GPU. Available only in GPU version.
    # pydarknet.set_cuda_device(0)

    net = Detector(bytes("cfg/yolov3.cfg", encoding="utf-8"), bytes("weights/yolov3.weights", encoding="utf-8"), 0,
                   bytes("cfg/coco.data", encoding="utf-8"))

    cap = cv2.VideoCapture(0)

    while True:
        r, frame = cap.read()
        if r:
            # start_time = time.time()

            # Only measure the time taken by YOLO and API Call overhead

            dark_frame = Image(frame)
            results = net.detect(dark_frame)
            del dark_frame

            # end_time = time.time()
            # print("Elapsed Time:",end_time-start_time)

            for cat, score, bounds in results:
                x, y, w, h = bounds
                cv2.rectangle(frame, (int(x-w/2),int(y-h/2)),(int(x+w/2),int(y+h/2)),(255,0,0))
                cv2.putText(frame, str(cat.decode("utf-8")), (int(x), int(y)), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 0))

            cv2.imshow("preview", frame)

        k = cv2.waitKey(1)
        if k == 0xFF & ord("q"):
            break

Commenting start_time = time.time()
![screenshot from 2018-10-24 00-14-39](https://user-images.githubusercontent.com/21198041/47383329-1ff7e600-d722-11e8-849e-2b7c72f598fd.png)

Uncommenting start_time = time.time()
![screenshot from 2018-10-24 00-16-16](https://user-images.githubusercontent.com/21198041/47383332-20907c80-d722-11e8-90a5-91ba9b1920f3.png)

**Comment by madhawav** [comment]
This is puzzling. Did you manage to solve the issue? 
Unfortunately, I can't think of any reason for this to happen. Uncommenting the line start_time = time.time() should not have any effect on the result.

**Comment by aj-ames** [comment]
Issue is resolved. It was puzzling indeed. All it took was a system restart. (I had not restarted my computer in days, I guess).
