### ISSUE TITLE
pydarknet.is_compiled_with_gpu returns false

### ISSUE THREAD

**Issue by Harsharma2308** [madhawav/YOLO3-4-Py#48]
I have followed the steps to run with gpu and opencv. But on importing pydarknet,
Both `pydarknet.is_compiled_with_gpu` and `pydarknet.is_compiled_with_opencv` return False

**Comment by frfrrfrrr** [comment]
Same thing for me.
And pydarknet.set_cuda_device(0) returns:
module 'pydarknet' has no attribute 'set_cuda_device'

**Comment by dquig** [comment]
I was running into the same issue trying to install from source with a custom darknet installation. It looks like the GPU environment variables is ignored if DARKNET_HOME is also set. T

https://github.com/madhawav/YOLO3-4-Py/blob/062de22fd3001f867404f65168dd1cb41f0f3a75/setup.py#L28

```python
if "GPU" in os.environ:
    if "DARKNET_HOME" in os.environ:
        logging.warning("GPU environment variable is skipped since DARKNET_HOME is specified")
    else:
        if int(os.environ["GPU"]) == 1:
            logging.info("Darknet will be compiled with GPU support")
            USE_GPU = True
        else:
            logging.info("Darknet will be compiled without GPU support")
            USE_GPU = False
```

This causes pydarknet to be compiled without the ability to set cuda device.

https://github.com/madhawav/YOLO3-4-Py/blob/062de22fd3001f867404f65168dd1cb41f0f3a75/pydarknet.pxd#L63

```python
IF USE_GPU == 1:
--
64 | void cuda_set_device(int n)
```

It looks to me like the `USE_GPU` variable should still be set in the case that `DARKNE_HOME` is also set.

**Comment by madhawav** [comment]
@dquig Thank you for showing the cause of issue. I will go through the setup script again and correct it.

**Comment by kartikpaigwar** [comment]
I am getting the same thing. Have you fixed that.
pydarknet.set_cuda_device(0) returns:
module 'pydarknet' has no attribute 'set_cuda_device'

**Comment by fspider** [comment]
Hello. I am going to run several processes.. One on Gpu 1 and another one on GPU 2.
So i am going to use set_gpu_device() function.
But it is showing this error.

> pydarknet.set_cuda_device(1)
> AttributeError: module 'pydarknet' has no attribute 'set_cuda_device'
> 
How can i do this?

**Comment by madhawav** [comment]
Fixed issue of ignoring GPU environment variable when custom DARKNET_HOME is set.
Refer #118
