### ISSUE TITLE
GPU install fails

### ISSUE THREAD

**Issue by tpim1102** [madhawav/YOLO3-4-Py#49]
![fkas](https://user-images.githubusercontent.com/37686950/47974288-f2c51380-e0e3-11e8-909e-ab3bcdccd28d.png)
![drfj](https://user-images.githubusercontent.com/37686950/47974485-cbbb1180-e0e4-11e8-880b-c20110f2b278.png)

**Comment by madhawav** [comment]
@tpim1102 Unfortunately we don't support Windows operating system.
