### ISSUE TITLE
Problem when compiling PyDarknet

### ISSUE THREAD

**Issue by guissoares** [madhawav/YOLO3-4-Py#5]
Hi,
I'm currently not being able to compile the Cython module. I followed the installation instructions, but after running the command `python3 setup.py build_ext --inplace`, I get the following error:
```
python setup.py build_ext --inplace
/home/user/anaconda3/envs/tensorflow-gpu/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build_ext
cythoning pydarknet.pyx to pydarknet.cpp
building 'pydarknet' extension
creating build
creating build/temp.linux-x86_64-3.5
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CV=1 -I/home/user/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/numpy/core/include -I/home/user/darknet/include -I/home/user/darknet/src -I/home/user/anaconda3/envs/tensorflow-gpu/include/python3.5m -c pydarknet.cpp -o build/temp.linux-x86_64-3.5/pydarknet.o 
gcc: error: : No such file or directory
error: command 'gcc' failed with exit status 1
```
I should also mention that I'm using conda to manage the required packages. Do you have any idea of what the problem is?
Thanks in advance!

**Comment by justinas-kazanavicius** [comment]
Read the end of https://github.com/madhawav/YOLO3-4-Py/issues/1

**Comment by fznply** [comment]
I also met this problem, do as below :
``
export PKG_CONFIG_PATH="$PY3/lib/pkgconfig:$PKG_CONFIG_PATH"
python3 setup.py build_ext --inplace
``
the error is gone

**Comment by madhawav** [comment]
@guissoares has the issue been resolved by following the solution mentioned by @fznply? 

Also, did you try installing from PIP as follow?
```pip install yolo34py-gpu```

**Comment by guissoares** [comment]
Thanks for the help! Yes, the problem has been solved with the instructions given by @fznply.
Also, it's nice to know that there's a pip package for it.
Thank you so much for your contribution, @madhawav!

**Comment by shivarajnaidu** [comment]
![image](https://user-images.githubusercontent.com/12374494/44137714-feca8b96-a08e-11e8-908d-50ac90080d7e.png)

![image](https://user-images.githubusercontent.com/12374494/44137755-2ec5dada-a08f-11e8-8303-4e3b43c5cf1f.png)


Getting this error if i try to install yolo34py using `pipenv install yolo34py`

**Comment by pherris** [comment]
screen shots should be banned from github issues
