### ISSUE TITLE
Python wrapper returns blank prediction

### ISSUE THREAD

**Issue by ssetty** [madhawav/YOLO3-4-Py#51]
Hello 
I am trying to use python wrapper https://pypi.org/project/yolo34py/ for model built using alexyAB https://github.com/AlexeyAB/darknet.

If I am using python wrapper predictions are blank. But if I use
darknet detector test data/obj.data yolo-obj.cfg yolo-obj_8000.weights test_image I can see predictions. I need some api wrapper for detected objects, bounding box coordinates and class label. Kindly help.

Thanks

**Comment by ssetty** [comment]
Do I need to set some probability threshold? May be values needs to be lowered?  Which setting is this?

**Comment by madhawav** [comment]
@ssetty You can have a cut-off based on the confidence score returned with a detection. 

```python
            results = net.detect(dark_frame)
            del dark_frame

            end_time = time.time()
            print("Elapsed Time:",end_time-start_time)

            for cat, score, bounds in results:
                if score > threshold:
                   x, y, w, h = bounds```

**Comment by h3ct0r** [comment]
Hi @ssetty did you find how to solve this problem? I'm having issues also with empty detections that are not happening if I use the standard darknet executable.
