### ISSUE TITLE
ImportError: /home/nvidia/.local/lib/python3.5/site-packages/pydarknet.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN9_IplImageC1ERKN2cv3MatE

### ISSUE THREAD

**Issue by eocene317** [madhawav/YOLO3-4-Py#57]

**Comment by madhawav** [comment]
@eocene317  Can you describe the issue further? 
- What were you doing when you got it? 
- What was on the console output
- What is your operating system, the version of CUDA etc. ?
