### ISSUE TITLE
distribute GPU 

### ISSUE THREAD

**Issue by me6ran** [madhawav/YOLO3-4-Py#58]
Hi
Thank you for your great work, I have been working with darkflow and yolo1, and it has the GPU option inside its module which enables us to use some portion of GPU rather than all of them. 
do you have this option on your module?

Thanks.

**Comment by madhawav** [comment]
Hi, 
Currently no but I will look into implementing this. 
It looks like a good feature to have.

**Comment by madhawav** [comment]
I believe darknet only consumes only the amount of video memory required by the network. it does not do a pre-allocation of entire GPU memory.
