### ISSUE TITLE
windows support 

### ISSUE THREAD

**Issue by goodtogood** [madhawav/YOLO3-4-Py#6]
Hi, there
Is there some plan for supporting windows?
thanks!

**Comment by SamNew1** [comment]
I am also interested in the windows version!

**Comment by virstark** [comment]
Another one here for the windows version approach. I've installed darknet of AlexeyAB and no problems so I think getting the wrapper to catch it up it's matter of time.

**Comment by haviduck** [comment]
Are there any benefits using this as opposed to Just using alexeys python version? Its running great on Windows here..
