### ISSUE TITLE
Starting from another client

### ISSUE THREAD

**Issue by phil100vol** [madhawav/YOLO3-4-Py#63]
Hello,

thanks for your great work. Long time I was looking for such a tool.
It **works perfectly** when I start any of your scripts or my own one using **from the same PC the script is located**.
Unfortunately when I try to run any of the python scripts in the directory "/YOLO3-4-Py" **from another PC** (f.e. from my Raspberry Pi) I get this error:

`from pydarknet import Detector, Image
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory`

I use sshpass. The same happens when I try to run a python script through another script (Same PC its working but from another one - see the error above.

Do you have any suggestion? Thanks and greetings

Phil

**Comment by madhawav** [comment]
Hi, 
This happens because when you log in via a remote terminal, the Cuda libraries are not added to LD_LIBRARY_PATH environment variable.
Usually, this would work. Run it before you start the scripts.
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64`

Before that, make sure libcudart.so.9.0 exists at /usr/local/cuda/lib64.

**Comment by phil100vol** [comment]
Hey,

I tried the command but nothing changed. Shall the export command give any output? I didn`t get one. Using sshpass provides the same error message. libcudart.so.9.0 exists at the path:

The output at the origin client:
`ls /usr/local/cuda/lib64 `

```
libaccinj64.so          libcusparse_static.a   libnppist_static.a
libaccinj64.so.9.0      libnppc.so             libnppisu.so
libaccinj64.so.9.0.176  libnppc.so.9.0         libnppisu.so.9.0
libcublas_device.a      libnppc.so.9.0.176     libnppisu.so.9.0.176
libcublas.so            libnppc_static.a       libnppisu_static.a
libcublas.so.9.0        libnppial.so           libnppitc.so
libcublas.so.9.0.176    libnppial.so.9.0       libnppitc.so.9.0
libcublas_static.a      libnppial.so.9.0.176   libnppitc.so.9.0.176
libcudadevrt.a          libnppial_static.a     libnppitc_static.a
libcudart.so            libnppicc.so           libnpps.so
libcudart.so.9.0        libnppicc.so.9.0       libnpps.so.9.0
libcudart.so.9.0.176    libnppicc.so.9.0.176   libnpps.so.9.0.176
libcudart_static.a      libnppicc_static.a     libnpps_static.a
libcufft.so             libnppicom.so          libnvblas.so
libcufft.so.9.0         libnppicom.so.9.0      libnvblas.so.9.0
libcufft.so.9.0.176     libnppicom.so.9.0.176  libnvblas.so.9.0.176
libcufft_static.a       libnppicom_static.a    libnvgraph.so
libcufftw.so            libnppidei.so          libnvgraph.so.9.0
libcufftw.so.9.0        libnppidei.so.9.0      libnvgraph.so.9.0.176
libcufftw.so.9.0.176    libnppidei.so.9.0.176  libnvgraph_static.a
libcufftw_static.a      libnppidei_static.a    libnvrtc-builtins.so
libcuinj64.so           libnppif.so            libnvrtc-builtins.so.9.0
libcuinj64.so.9.0       libnppif.so.9.0        libnvrtc-builtins.so.9.0.176
libcuinj64.so.9.0.176   libnppif.so.9.0.176    libnvrtc.so
libculibos.a            libnppif_static.a      libnvrtc.so.9.0
libcurand.so            libnppig.so            libnvrtc.so.9.0.176
libcurand.so.9.0        libnppig.so.9.0        libnvToolsExt.so
libcurand.so.9.0.176    libnppig.so.9.0.176    libnvToolsExt.so.1
libcurand_static.a      libnppig_static.a      libnvToolsExt.so.1.0.0
libcusolver.so          libnppim.so            libOpenCL.so
libcusolver.so.9.0      libnppim.so.9.0        libOpenCL.so.1
libcusolver.so.9.0.176  libnppim.so.9.0.176    libOpenCL.so.1.0
libcusolver_static.a    libnppim_static.a      libOpenCL.so.1.0.0
libcusparse.so          libnppist.so           stubs
libcusparse.so.9.0      libnppist.so.9.0
```
Of course at my pi this directory doesn`t exist.
