### ISSUE TITLE
AttributeError: pydarknet.detector' object has no attribute 'state_dict'

### ISSUE THREAD

**Issue by yizhaoyanbo** [madhawav/YOLO3-4-Py#64]
I wanna to convert the yolov3-tiny model with pytorch to onnx model. Following is my code.

'
model = pydarknet.Detector(bytes(cfg_file, encoding="utf-8"), bytes(weights_file, encoding="utf-8"), 0, bytes(classes_file, encoding="utf-8"))

batch_size=1

onnx_path ="onnx_model.onnx"

dummy_input = Variable(torch.randn(batch_size, 3, 224, 224), requires_grad=True)

torch_out = torch.onnx.export(model, dummy_input, onnx_path )
'

But this error occurs: AttributeError: pydarknet.detector' object has no attribute 'state_dict'.  Does anyone have the same problem? thanks very much.

**Comment by madhawav** [comment]
Hi
Please note that pydarknet does not support conversion of models to PyTorch.
