### ISSUE TITLE
 how can I limit the use of the gpu?

### ISSUE THREAD

**Issue by FelipeSanchezCalzada** [madhawav/YOLO3-4-Py#66]
Hello, excellent work!
I need to limit the dedicated memory to yolo because my graph (1050 Ti 4GB) always overflows and the program gives error.
I know from other libraries (like tensorflow for example) that lowering the dedicated memory is quickly solved.

**Comment by madhawav** [comment]
Hi,
You have to set `batch` and `subdivisions` to 1 in yolov3.cfg file. You can do it by setting the lines 
batch=64 and subdivisions=16 in the above-mentioned file. 

If you download the models using the [download_models.sh](https://github.com/madhawav/YOLO3-4-Py/blob/master/download_models.sh) script, this issue should be fixed automatically.

**Comment by madhawav** [comment]
If that also fails, just check whether any other process is hogging the GPU memory. Darknet only takes memory as much as it needs. (Unlike earlier versions of Tensorflow, which locks up the entire GPU memory)
