### ISSUE TITLE
get_darknet_image() flips RGB to BGR but darknet expects RGB

### ISSUE THREAD

**Issue by series8217** [madhawav/YOLO3-4-Py#67]
If I'm following the code correctly, it looks like there is an erroneous reordering of color channels in `get_darknet_image()`:

```
image get_darknet_image(const Mat &input){
    // Darknet requires BGR order
    Mat flipped;
    cvtColor(input, flipped, CV_RGB2BGR);
```

The comment "Darknet requires BGR order" is not correct -- In fact, darknet expects RGB-ordered images. This can be seen in the BGR->RGB conversion darknet performs when loading openCV images. Refer to [image_opencv.load_image_cv()](https://github.com/pjreddie/darknet/blob/master/src/image_opencv.cpp), which calls [`mat_to_image()` and `rgbgr_image(im)`](https://github.com/pjreddie/darknet/blob/master/src/image_opencv.cpp#L61).

**Comment by madhawav** [comment]
@series8217 Thank you for bringing attention to this. 
Let me go through the code in depth and get back to you. This could be a fact I have overlooked.

**Comment by VideoPlayerCode** [comment]
@madhawav There's even more proof that Darknet is RGB based here: https://github.com/pjreddie/darknet/issues/427

:-)
