### ISSUE TITLE
Batch inference

### ISSUE THREAD

**Issue by levan92** [madhawav/YOLO3-4-Py#69]
Thank you for this very useful python wrapper for darknet! It has served us very well. 

Was wondering if you have plans to extend the functionality of this wrapper to include batch inferencing? i.e. take in a batch of images as a NxWxHxC matrix then pass it into darknet's function for batch inference? (assuming here that darknet supports batch inference)

**Comment by madhawav** [comment]
I had a brief look at this but couldn't find cases where batch inference is used with darknet. There are some ongoing discussion on this feature though.
1) https://github.com/pjreddie/darknet/issues/997

Until darknet supports it, this won't be possible.
