### ISSUE TITLE
Connecting yolo with zed camera

### ISSUE THREAD

**Issue by Lakshaysharma048** [madhawav/YOLO3-4-Py#71]
Hi, 
i have seen three variants of application are given- webcam, video and image.

how can i run the algorithm using my zed camera.

what and where are the necessary changes to make.

thanks.

**Comment by madhawav** [comment]
Hi, 
It seems Zed Camera can be accessed from OpenCV as a normal inbuilt Web Cam or a USB connected Web Cam. 
https://www.stereolabs.com/docs/opencv/

You will need to update the line `cap = cv2.VideoCapture(0)` of [webcam_demo.py](https://github.com/madhawav/YOLO3-4-Py/blob/master/webcam_demo.py) with correct index used to identify the ZED camera. (In the above example, index 0, which represent the default WebCamera is used.) Maybe the Zed Camera is occupying the index 1.

`cap = cv2.VideoCapture(0)`

**Comment by madhawav** [comment]
When you connect the Zed Camera as explained, you will get the two cameras inputs in a single image. You will have to split them and then feed to YOLO34Py. 

Check the code in UVC section of https://www.stereolabs.com/docs/opencv/.
