### ISSUE TITLE
cannot find -ldarknet

### ISSUE THREAD

**Issue by Lakshaysharma048** [madhawav/YOLO3-4-Py#75]
Hi,
Using Cuda 10.0
opencv 3.4.2
conda python 3.5 
cython, numpy- all requirements met.

While running "Pip3 install yolo34py-gpu",
i am getting this error.

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE_CV=1 -I/home/mmvc/.local/lib/python3.5/site-packages/numpy/core/include -I/tmp/darknet/darknet-yolo34py-intergration/include -I/tmp/darknet/darknet-yolo34py-intergration/src -I/usr/include/python3.5m -c bridge.cpp -o build/temp.linux-x86_64-3.5/bridge.o -I/usr/include/python3.5m -I/usr/include/x86_64-linux-gnu/python3.5m -I/usr/local/include/opencv -I/usr/local/include
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/pydarknet.o build/temp.linux-x86_64-3.5/bridge.o -L. -L./__libdarknet -ldarknet -lm -lpthread -o build/lib.linux-x86_64-3.5/pydarknet.cpython-35m-x86_64-linux-gnu.so -lpython3.5m -L/usr/local/lib -lopencv_cudabgsegm -lopencv_cudaobjdetect -lopencv_cudastereo -lopencv_shape -lopencv_stitching -lopencv_cudafeatures2d -lopencv_superres -lopencv_cudacodec -lopencv_videostab -lopencv_cudaoptflow -lopencv_cudalegacy -lopencv_calib3d -lopencv_features2d -lopencv_objdetect -lopencv_highgui -lopencv_videoio -lopencv_photo -lopencv_imgcodecs -lopencv_cudawarping -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_video -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_cudaarithm -lopencv_viz -lippicv -lopencv_core -lopencv_cudev -Wl,-rpath,/home/mmvc/.local/lib/python3.5/site-packages/__libdarknet -Wl,-rpath,/usr/local/lib/python3.5/dist-packages/__libdarknet -Wl,-rpath,/usr/lib/python3/dist-packages/__libdarknet
    /usr/bin/ld: cannot find -ldarknet
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-g++' failed with exit status 1

can you please help here.

**Comment by Lakshaysharma048** [comment]
Also, i am using ubuntu 16.04

**Comment by madhawav** [comment]
Hi, it seems darknet compilation has failed. Can you provide the complete console output?

**Comment by Lakshaysharma048** [comment]
Definitely, please find the full error below:

pip3 install yolo34py-gpu
Collecting yolo34py-gpu
  Using cached https://files.pythonhosted.org/packages/dc/a3/12c668e54109c5469a8312d757b357dda0b2efc2150043b76b58f6ba75c3/yolo34py-gpu-0.1rc12.tar.gz
Requirement already satisfied: cython>=0.27 in ./.local/lib/python3.5/site-packages (from yolo34py-gpu) (0.28.2)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from yolo34py-gpu) (2.9.1)
Requirement already satisfied: numpy in ./.local/lib/python3.5/site-packages (from yolo34py-gpu) (1.14.2)
Building wheels for collected packages: yolo34py-gpu
  Running setup.py bdist_wheel for yolo34py-gpu ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-i1ss6qxn/yolo34py-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-0opy12om --python-tag cp35:
  INFO:root:Darknet will be compiled with GPU support
  INFO:root:Compiling wrapper with OpenCV
  INFO:root:Selected Darknet Branch: yolo34py-intergration from Darknet Fork 'https://github.com/madhawav/darknet/'
  /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
    warnings.warn(msg)
  /usr/lib/python3/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.1.rc12' to '0.1rc12'
    normalized_version,
  running bdist_wheel
  running build
  INFO:root:Temp Path: /tmp/darknet
  INFO:root:Downloading darknet
  INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): github.com
  INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): codeload.github.com
  INFO:root:Extracting darknet
  INFO:root:Building darknet
  /usr/bin/ld: cannot find -lippicv
  /usr/bin/ld: cannot find -lcuda
  collect2: error: ld returned 1 exit status
  make: *** [libdarknet.so] Error 1
  running build_py
  INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
  INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/__libdarknet
  copying __libdarknet/__init__.py -> build/lib.linux-x86_64-3.5/__libdarknet
  running egg_info
  writing dependency_links to yolo34py_gpu.egg-info/dependency_links.txt
  writing requirements to yolo34py_gpu.egg-info/requires.txt
  writing yolo34py_gpu.egg-info/PKG-INFO
  writing top-level names to yolo34py_gpu.egg-info/top_level.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '__libdarknet/libdarknet.so'
  writing manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
  running build_ext
  skipping 'pydarknet.cpp' Cython extension (up-to-date)
  building 'pydarknet' extension
  creating build/temp.linux-x86_64-3.5
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE_CV=1 -I/home/mmvc/.local/lib/python3.5/site-packages/numpy/core/include -I/tmp/darknet/darknet-yolo34py-intergration/include -I/tmp/darknet/darknet-yolo34py-intergration/src -I/usr/include/python3.5m -c pydarknet.cpp -o build/temp.linux-x86_64-3.5/pydarknet.o -I/usr/include/python3.5m -I/usr/include/x86_64-linux-gnu/python3.5m -I/usr/local/include/opencv -I/usr/local/include
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from /home/mmvc/.local/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                   from /home/mmvc/.local/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /home/mmvc/.local/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from pydarknet.cpp:580:
  /home/mmvc/.local/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE_CV=1 -I/home/mmvc/.local/lib/python3.5/site-packages/numpy/core/include -I/tmp/darknet/darknet-yolo34py-intergration/include -I/tmp/darknet/darknet-yolo34py-intergration/src -I/usr/include/python3.5m -c bridge.cpp -o build/temp.linux-x86_64-3.5/bridge.o -I/usr/include/python3.5m -I/usr/include/x86_64-linux-gnu/python3.5m -I/usr/local/include/opencv -I/usr/local/include
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/pydarknet.o build/temp.linux-x86_64-3.5/bridge.o -L. -L./__libdarknet -ldarknet -lm -lpthread -o build/lib.linux-x86_64-3.5/pydarknet.cpython-35m-x86_64-linux-gnu.so -lpython3.5m -L/usr/local/lib -lopencv_cudabgsegm -lopencv_cudaobjdetect -lopencv_cudastereo -lopencv_shape -lopencv_stitching -lopencv_cudafeatures2d -lopencv_superres -lopencv_cudacodec -lopencv_videostab -lopencv_cudaoptflow -lopencv_cudalegacy -lopencv_calib3d -lopencv_features2d -lopencv_objdetect -lopencv_highgui -lopencv_videoio -lopencv_photo -lopencv_imgcodecs -lopencv_cudawarping -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_video -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_cudaarithm -lopencv_viz -lippicv -lopencv_core -lopencv_cudev -Wl,-rpath,/home/mmvc/.local/lib/python3.5/site-packages/__libdarknet -Wl,-rpath,/usr/local/lib/python3.5/dist-packages/__libdarknet -Wl,-rpath,/usr/lib/python3/dist-packages/__libdarknet
  /usr/bin/ld: cannot find -ldarknet
  collect2: error: ld returned 1 exit status
  error: command 'x86_64-linux-gnu-g++' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for yolo34py-gpu
  Running setup.py clean for yolo34py-gpu
Failed to build yolo34py-gpu
Installing collected packages: yolo34py-gpu
  Running setup.py install for yolo34py-gpu ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-i1ss6qxn/yolo34py-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-mu6mlc4j/install-record.txt --single-version-externally-managed --compile:
    INFO:root:Darknet will be compiled with GPU support
    INFO:root:Compiling wrapper with OpenCV
    INFO:root:Selected Darknet Branch: yolo34py-intergration from Darknet Fork 'https://github.com/madhawav/darknet/'
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    /usr/lib/python3/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.1.rc12' to '0.1rc12'
      normalized_version,
    running install
    running build
    INFO:root:Temp Path: /tmp/darknet
    INFO:root:Downloading darknet
    INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): github.com
    INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): codeload.github.com
    INFO:root:Extracting darknet
    INFO:root:Building darknet
    /usr/bin/ld: cannot find -lippicv
    /usr/bin/ld: cannot find -lcuda
    collect2: error: ld returned 1 exit status
    make: *** [libdarknet.so] Error 1
    running build_py
    INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
    INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/__libdarknet
    copying __libdarknet/__init__.py -> build/lib.linux-x86_64-3.5/__libdarknet
    running egg_info
    writing top-level names to yolo34py_gpu.egg-info/top_level.txt
    writing yolo34py_gpu.egg-info/PKG-INFO
    writing requirements to yolo34py_gpu.egg-info/requires.txt
    writing dependency_links to yolo34py_gpu.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '__libdarknet/libdarknet.so'
    warning: no files found matching 'pydarknet.cpp'
    writing manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
    running build_ext
    cythoning pydarknet.pyx to pydarknet.cpp
    building 'pydarknet' extension
    creating build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE_CV=1 -I/home/mmvc/.local/lib/python3.5/site-packages/numpy/core/include -I/tmp/darknet/darknet-yolo34py-intergration/include -I/tmp/darknet/darknet-yolo34py-intergration/src -I/usr/include/python3.5m -c pydarknet.cpp -o build/temp.linux-x86_64-3.5/pydarknet.o -I/usr/include/python3.5m -I/usr/include/x86_64-linux-gnu/python3.5m -I/usr/local/include/opencv -I/usr/local/include
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/mmvc/.local/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                     from /home/mmvc/.local/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/mmvc/.local/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from pydarknet.cpp:580:
    /home/mmvc/.local/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE_CV=1 -I/home/mmvc/.local/lib/python3.5/site-packages/numpy/core/include -I/tmp/darknet/darknet-yolo34py-intergration/include -I/tmp/darknet/darknet-yolo34py-intergration/src -I/usr/include/python3.5m -c bridge.cpp -o build/temp.linux-x86_64-3.5/bridge.o -I/usr/include/python3.5m -I/usr/include/x86_64-linux-gnu/python3.5m -I/usr/local/include/opencv -I/usr/local/include
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/pydarknet.o build/temp.linux-x86_64-3.5/bridge.o -L. -L./__libdarknet -ldarknet -lm -lpthread -o build/lib.linux-x86_64-3.5/pydarknet.cpython-35m-x86_64-linux-gnu.so -lpython3.5m -L/usr/local/lib -lopencv_cudabgsegm -lopencv_cudaobjdetect -lopencv_cudastereo -lopencv_shape -lopencv_stitching -lopencv_cudafeatures2d -lopencv_superres -lopencv_cudacodec -lopencv_videostab -lopencv_cudaoptflow -lopencv_cudalegacy -lopencv_calib3d -lopencv_features2d -lopencv_objdetect -lopencv_highgui -lopencv_videoio -lopencv_photo -lopencv_imgcodecs -lopencv_cudawarping -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_video -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_cudaarithm -lopencv_viz -lippicv -lopencv_core -lopencv_cudev -Wl,-rpath,/home/mmvc/.local/lib/python3.5/site-packages/__libdarknet -Wl,-rpath,/usr/local/lib/python3.5/dist-packages/__libdarknet -Wl,-rpath,/usr/lib/python3/dist-packages/__libdarknet
    /usr/bin/ld: cannot find -ldarknet
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-g++' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-i1ss6qxn/yolo34py-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-mu6mlc4j/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-i1ss6qxn/yolo34py-gpu/

**Comment by Lakshaysharma048** [comment]
Hi Madhawav,

do you have any solution for this.

**Comment by albertoZurini** [comment]
Same issue after installing CUDA 10. Now I will revert to CUDA 9 and tell you further updates.

**Comment by Lakshaysharma048** [comment]
Hi @albertoZurini ,

I resolved the issue by installing Cuda 9.0

Don't install opencv using "pip install opencv"

Install it from Source by building opencv.

This will resolve the above issue.

**Comment by Lakshaysharma048** [comment]
Hi @madhawav ,

My issue got resolved but when running webcam_demo.py file, 

it is saying error at line 3:
from pydarknet import Detector, Image.

ImportError: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/mmvc/anaconda2/envs/ZED/lib/libpng16.so.16)

**Comment by madhawav** [comment]
@Lakshaysharma048 Did you manage to resolve the issue?

I have not tried YOLO34Py with the version of Python that comes with Anaconda. However, I found the following in StackOverflow which seem to discuss on a similar problem.
https://stackoverflow.com/questions/48306849/lib-x86-64-linux-gnu-libz-so-1-version-zlib-1-2-9-not-found
