### ISSUE TITLE
output of Yolo3-4-py differs from output of darknet

### ISSUE THREAD

**Issue by ahmed-nady** [madhawav/YOLO3-4-Py#76]
@madhawav 
Firstly, i appreciate your effort in doing this wrapper. But i used it and found that the output of this wrapper differs from Darknet output. Can you tell me the reason for that? and how to produce the output of darknet using this wrapper?

**Comment by madhawav** [comment]
Hi,
Thank you for raising this issue. What kind of differences did you notice? Is it a difference in the scores given? or was their more substantial changes?

**Comment by ahmed-nady** [comment]
@madhawav 
sorry for the late replay.
i made verification on this problem and i found you set default values for nms=0.45 ,thresh=0.5. But i was using different values for these parameters in darknet. So, i used the same values for parameters and i found the output of pydarknet and darknet the same.

**Comment by camilosilva91** [comment]
Hi Guys, 
I have the same issue, I'm using the same image on both Pydarknet and Darknet, but the bounding boxes are't the same, and the accuracy isn't either, furthermore,  Pydarknet detect two non-existing objects. How can you configure the **nms** and **thresh** parameters?

this is my network settings

```
net = Detector(	bytes("darknet-master/cfg/yolo-obj.cfg", encoding="utf-8"), 
				bytes("darknet-master/backup/yolo-obj_3000.weights", encoding="utf-8"), 
				0, 
				bytes("darknet-master/data/obj2.data",encoding="utf-8"))
```

**Comment by ahmed-nady** [comment]
@camilosilva91 
you can set the values for  nms and thresh parameters
using this:
detections = net.detect(img_darknet,thresh=0.6,nms=0.45)

**Comment by camilosilva91** [comment]
Thanks for answer so soon @ahmed-nady. I found that a moment ago, but I still have a problem. In Pydarknet prediction I get two bounding boxes out of the image (with the Y axis in negative), and I can't  get the same precision as with Darknet. I've tried different combinations of thresh, hier_thresh and nms, but I don't achieve the same result. I found the default value used by YOLOv3 for **thresh** and **hier_thresh**, but I couldn't find the default value of Non-Maximum Suppression (nms). In your case, what values did you use to obtain the same result in both?
Regards.

**Comment by madhawav** [comment]
Hi guys,
Sorry for the delay. 

**Can you try reversing the order of color channels in the input? (E.g. RGB to BGR).** Please let me know if it fixes your issue.

I feel this issue can be related to the following.
https://github.com/madhawav/YOLO3-4-Py/issues/67
https://github.com/madhawav/YOLO3-4-Py/pull/70
