### ISSUE TITLE
FPS yolov3 compared to YOLO3-4-Py

### ISSUE THREAD

**Issue by icklerly** [madhawav/YOLO3-4-Py#78]
Hi there, 

we tested your framework on a Jetson TX2 and made a finding that might interest you:
In comparison to the native darknet execution your python-wrapper has about 10% less FPS.
Is that a behaviour that you are aware of? If so: Would you mind to explain where the extra time goes into?

FPS in detail:
detectnet yolov3 with image size 224 x 224 ~ 10 FPS
yolo34py yolov3 with image size 224 x 224 ~ 8.8 FPS

detectnet yolov3-tiny with image size 224 x 224 ~ 29 FPS
yolo34py yolov3-tiny with image size 224 x 224 ~ 27 FPS

**Comment by madhawav** [comment]
Hi,
Thank you for your statistics. 

Yes, I am aware of this. This additional time is consumed by the conversion of Numpy input array to darknet image, which happens during an inference call. In fact, I have already mentioned about this extra overhead in [this article](https://medium.com/@madhawavidanapathirana/not-just-another-yolo-v3-for-python-79da6c3af082). 

In the measurements I obtained for the article about a year ago, I witnessed about 11% additional overhead for processing 1920x1080 resolution input. 

Can you let me know the installation steps you followed? Did you install the version of the wrapper with OpenCV support?
