### ISSUE TITLE
How to change nms and confidence threshold in python wrapper?

### ISSUE THREAD

**Issue by smajida** [madhawav/YOLO3-4-Py#8]
Hi

I wanted to ask whether there is possibility to change nms and confidence threshold in python wrapper. Right now, I need to modify this default parameters to get good results.

**Comment by madhawav** [comment]
Hi, 
You can filter results using the "score" value (2nd parameter of tuple) provided in results of net.detect() function.

For example, look at the **```if score > 0.5:```** line of below sample code.

```python
            dark_frame = Image(frame)
            results = net.detect(dark_frame)
            del dark_frame

            for cat, score, bounds in results:
                if score > 0.5:
                    x, y, w, h = bounds
                    cv2.rectangle(frame, (int(x-w/2),int(y-h/2)),(int(x+w/2),int(y+h/2)),(255,0,0))
```

Did you try this approach?

**Comment by smajida** [comment]
But small points, the detections are not identical when I use original c++ wrapper.

**Comment by madhawav** [comment]
@smajida Can you send me some more details? Like maybe screen shots on certain scenarios where you noticed a difference? 

If you can send, it would be of great help!

**Comment by smajida** [comment]
@madhawav sure. Right now. I do not have my laptop with me. I will send it to you soon. BTW, are you interested in an internship in German Aerospace Center(DLR)?

**Comment by madhawav** [comment]
@smajida Thank you for the offer! Where can I find more information? 

Also, how about opportunities to do higher studies? I recently completed my Bachelors Degree in Computer Science. Right now I am looking for opportunities to do higher studies.

**Comment by VitaliKaiser** [comment]
Hi,

but how would I lower the minimum threshold? If I get it right, after calling

results = net.detect(dark_frame)

I only get the results above the default confidence threshold of 0.25. I would not get results with a lower threshold. In my case I would like to get, e.g., every result above 0.01. How would I manage that?

Best,

Vitali

**Comment by VitaliKaiser** [comment]
OK I found the answer myself in the code.
This are the function parameters of **detect**:
`def detect(self, Image image, float thresh=.5, float hier_thresh=.5, float nms=.45):`

**Comment by sushant1727** [comment]
Is there a way to print the confidence level?

**Comment by sushant1727** [comment]
@VitaliKaiser @madhawav Where can I find the parameters of net.detect() function & pydarknet files where it imports Detector, Image.
(I installed using pip yolo gpu version.)

**Comment by madhawav** [comment]
@smajida Any updates on the screenshots (on scenarios where you noticed detection differences) ?
