### ISSUE TITLE
Active Window Grab

### ISSUE THREAD

**Issue by OzgunKB** [madhawav/YOLO3-4-Py#82]
Hello
I don't want a picture or webcam detection. Can I have Windows detect it in the active window?
Like in these codes.

Can you look at this sample?
https://www.codepile.net/pile/mz3KN0zd

**Comment by madhawav** [comment]
Hi, 
YOLO3-4-Py currently does not support windows. However, in Linux, you can couple it with a library like pyscreenshot as described below.

https://stackoverflow.com/questions/43520757/imagegrab-alternative-in-linux
