### ISSUE TITLE
Error to run on GPU

### ISSUE THREAD

**Issue by kartikpaigwar** [madhawav/YOLO3-4-Py#85]
$python webcam_demo.py
Traceback (most recent call last):
  File "webcam_demo.py", line 10, in <module>
    pydarknet.set_cuda_device(0)
AttributeError: module 'pydarknet' has no attribute 'set_cuda_device'

**Comment by madhawav** [comment]
Hi, how did you install? 
If you installed by source, you need to set the environment variables that install the GPU version.
