### ISSUE TITLE
CPU not using all cores while passing net

### ISSUE THREAD

**Issue by MasterMindSudo** [madhawav/YOLO3-4-Py#86]
Hello, I am using the cpu-only version and it takes about 4 seconds per frame on my 4 core 8 threads machine, and its only using 2 threads at a time, I am running on linux ubuntu, how to enable multicore functionality?

**Comment by madhawav** [comment]
Hi,
This is a limitation from the underlying Darknet implementation. So for single image inference, a solution is unlikely.

But, if you are processing multiple frames, you can have a multiprocessing arrangement with queues. A scheduler can schedule frames across multiple processes holding a detector.
