### ISSUE TITLE
confident drop when using wrapper

### ISSUE THREAD

**Issue by MasterMindSudo** [madhawav/YOLO3-4-Py#87]
When I use the detector from darknet, my confidence is 0.82 as comparing to using the wrapper with the same cfg and weight, i only get 0.4 on the same image, have i done something wrong?

i have tried converting the colour channel  or resizing the image but the confidence only goes even lower to 0.33

FYI, i am using my own model and weight
Please advice, thanks

**Comment by madhawav** [comment]
It could that you are using a different version of darknet than what is used by this wrapper. Did you refer to the same darknet installation by setting the DARKNET_HOME environment variable?
