### ISSUE TITLE
custom version of Darknet(AlexeyAB_darknet)

### ISSUE THREAD

**Issue by ahmed-nady** [madhawav/YOLO3-4-Py#89]
I used this python wrapper for darknet and i fount that it's useful. but i can not install this wrapper based on custom version of Darknet(AlexeyAB_darknet) [https://github.com/AlexeyAB/darknet]
.This error message appears "error: command 'gcc' failed with exit status 1"

**Comment by madhawav** [comment]
Hi,
Unfortunately, this wrapper does not support YOLO V4 available at the above fork.
