### ISSUE TITLE
No difference between cuda_device and not ?? 

### ISSUE THREAD

**Issue by theo574** [madhawav/YOLO3-4-Py#92]
Hi! 
I've done the installation with cuda, and in fact when import pydarknet i can use pydarknet.set_cuda_device(0).
Using yolov3 i see very slow operation, then i tried to use yolov3-tiny and now 7FPS.
Next i tried to comment pydarknet.set_cuda_device(0) and i see the same result.
What is the cause?
Where did i wrong?

Thaaaaank youuuuu

**Comment by madhawav** [comment]
Hi,
Are you able to observe GPU activity when yolov3 is running with CUDA? (You can test this by running `watch nvidia-smi` in terminal). 

In case if you are still investigating this issue, please re-open.
