### ISSUE TITLE
YOLO3-4-Py Multiprocessing issue

### ISSUE THREAD

**Issue by rshigemura** [madhawav/YOLO3-4-Py#94]
I'm trying hard to use YOLO34Py objects (Image and Detector) in a multiprocess fashion. That is, to pass both (Image and Detector) objects using Python process queues or manager with namespaces. The benefit is twofold: to separate the Image conversion (CPU) and detection (GPU) in parallel processes, and to leverage the detect object across  multiple flows of images from multiple sources, in such way that GPU doesnt have to wait just one source of images.

However, I'm getting the following error:

_TypeError: pydarknet.Detector cannot be converted to a Python object for pickling_

I tried other approaches, like multiprocessing.sharedctypes, dill, but none worked. I suspect there is some way of pickle the Detector class, but being written in cython I have no idea how it could be done.

Someone already tried to use pydarknet in multiprocess fashion?

**Comment by madhawav** [comment]
Hi, 
Making a shared Detector and accessing it from multiple processes will probably not work. What I can suggest you is to have Detector objects created after invoking each process.
