### ISSUE TITLE
yolov3-tiny compatibility 

### ISSUE THREAD

**Issue by nihadern** [madhawav/YOLO3-4-Py#95]
I am trying to use the yolov3-tiny weights and config files to test performance. I keep encountering a segmentation fault and no other error to be seen. I followed the example code from the pip documentation:

```
from pydarknet import Detector, Image
import cv2

net = Detector(bytes("cfg/yolov3-tiny.cfg", encoding="utf-8"), bytes("weights/yolov3-tiny.weights", encoding="utf-8"), 0, bytes("cfg/coco.data",encoding="utf-8"))

img = cv2.imread('humans.jpg')
img_darknet = Image(img)

results = net.detect(img_darknet)

for cat, score, bounds in results:
    x, y, w, h = bounds
    cv2.rectangle(img, (int(x - w / 2), int(y - h / 2)), (int(x + w / 2), int(y + h / 2)), (255, 0, 0), thickness=2)
    cv2.putText(img,str(cat.decode("utf-8")),(int(x),int(y)),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,0))

cv2.imshow("output", img)
cv2.waitKey(0)
cv2.destroyAllWindows();

```

**Comment by AsharFatmi** [comment]
Did you find the solution??

**Comment by erencerman** [comment]
I have used
 1)my own trained yolo-tiny.cfg
2)yolo-tiny.weight
3) put the obj.names into the directory and defined the path to it, in a datafile_leading_to_names.data file.

It worked with yolo34py on jetson nano.So theoretically yolo-tiny works with yolo34py

**Comment by madhawav** [comment]
I just tried the docker code with yolo-tiny models and it worked. Please find the code changes I did in the patch below. 

[yolo-v3-tiny-coco-patch.zip](https://github.com/madhawav/YOLO3-4-Py/files/4011857/yolo-v3-tiny-coco-patch.zip)
