### ISSUE TITLE
What is the difference between YOLO3-4-Py and Darkflow 

### ISSUE THREAD

**Issue by innjoshka** [madhawav/YOLO3-4-Py#97]
Question:
As I understand correctly both solve gives Python wrappers over Darknet C project. I believe many people are wish to know the difference between these two wrappers. Could you explain all pros and cons. 

Thanks for the great project and in advance for the answer

**Comment by madhawav** [comment]
I am not very familiar with the Dark-Flow project, but by the looks of it, Dark Flow is a converter of Darknet models to Tensorflow models. So, after converting a Darknet model such as YOLOV3 to Tensorflow, one can do the rest of the work using Tensorflow. (Of course, for YOLO V3, there should be good pre-trained models already in Tensorflow, so one does not have to do this conversion).

YOLO34Py is, on the other hand, a wrapper on YOLO 3 authors implementation, which is written on Darknet. Generally, it is very easy to configure YOLO34Py so It's probably a good place to start off. But, if you want to do more advanced work such as modifying the network, YOLO34Py will not be able to help you. 

Looking forward to others opinion as well.
